ministryofjustice/hmpps-accredited-programmes-api

.github/PULL_REQUEST_TEMPLATE.md

Adds a PR template (this one!) to remind us to do things like link relevant trello tickets, update environment variables, add ADRs when opening a PR.

Add PR template to standardise PR descriptions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/controller/CoursesController.kt
src/main/resources/static/api.yml

* `api.yml `- renamed property `programmePrerequisites` to `courseRequisites` in the schema for `Course`.  
* Updated `CourseController` accordingly

:bug: programmePrerequisites property of Course should be named coursePrerequisites.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/HmppsAccreditedProgrammesApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/NotFoundException.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/CourseServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesControllerTest.kt

Trello ticket [346]( https://trello.com/c/90RhMAnl/346-add-api-endpoint-for-an-individual-courseoffering)
* New GET `/courses/{courseId}/offerings/{offeringId}` end-point returns information about a single course offering
* Returns 404 NOT_FOUND if the ids do not select an offering
* Added full stack test of new end-point. (Integration test)
Notes:
* hmps-approved-premises-api uses  library ["org.zalando:problem-spring-web-starter:0.27.0"](https://github.com/zalando/problem-spring-web)  to assist with handling HTTP error responses following [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807).  Currently this application does not do so and does not adhere to the response format defined in rfc7807. Should it?
* The `GET /courses/{courseId}/offerings` returns an empty response when the …

Implement the GET /courses/{courseId}/offerings/{offeringId} end-point

---

build.gradle.kts
docker-compose.arm64.yml
docker-compose.yml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
script/all_courses
script/get_token
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
src/main/resources/application-local.yml
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/fixture/JwtAuthHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesControllerTest.kt

Trello [328](https://trello.com/c/tF7qCm3p/328-add-hmpps-auth-to-api)
This change introduces a new spring boot configuration parameter `hmpps.auth.url` which as an environment variable is `HMPPS_AUTH_URL`.
Required for integration testing.
Use spring-boot ouath2 framework, test for guarded and unguarded end-points.
The hmpps auth end-point url is configurable as `HMPPS_AUTH_URL`
A valid token must be included in requests to guarded end-points. This script fetches suitable tokens from the hmpps-auth instance deployed in docker. Requires curl and jq.
This script performs a 'GET /courses' request to a locally running instance of the application. It includes a valid bearer token, retrieved using the get_token script,  in the Authentication header

328 :sparkles: Add hmpps auth to api

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/CourseServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesControllerTest.kt

Trello [416 Add endpoint for /courses/id](https://trello.com/c/2lDAgqm2/416-add-endpoint-for-courses-id)
Add the end-point with tests for service and controller.

:sparkles: Add a 'GET /courses/{courseId}' endpoint to return info for one course or 404 Not Found.

---

.trivyignore
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/HmppsAccreditedProgrammesApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/SecurityConfiguration.kt
src/main/resources/logback-spring.xml

Updates recommended by renovate bot. 
* Gradle plugin uk.gov.justice.hmpps.gradle-spring-boot updated to version 5.1.4
* Gradle plugin org.openapi.generator updated to version 6.6.0
* Configure openApi generator to generate code compatible with Spring Boot 3 (package javax renamed to jakarta)
* Update package dependencies in code from javax.servlet etc to jakarta.servlet
* Update Spring Boot web security configuration to use Spring Security 6 kotlin configuration style. (class SecurityConfiguration)
* Correct problems with Logback configuration when spring profile is neither 'dev' or 'stdout' (remove Application Insights logback appender)

:arrow_up: Update Gradle plugins

---

.circleci/config.yml
build.gradle.kts
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/contract/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/fixture/JwtAuthHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/PactContractTest.kt
src/test/resources/application-test.yml

Trello: [325](https://trello.com/c/8ajNIPEn/325-set-up-pact-on-the-api)
Add the Pact `junit5spring` runner to the Gradle `testImplementation` configuration 
Pulls the latest contracts for provider 'Accredited Programmes API' from the pact broker. 
Verifies  the API server against all matching contracts - adding a valid token to the `Authorization` header in each request.
Use Spring Boot facilities to inject and program a mocked version of CourseService when verifying pacts.
Saved in directory build/pact
Update `build.gradle.kts` to provide the environment variables and values needed by junit5spring so that the Pact validation results can be published to the Pact server by the CircleCI workflow.
Update the CircleCI configuration so that the Pact provider verification results are published …

325 :sparkles: Add Pact provider contract verification

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/Audience.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/transformer/Transformers.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/transformer/TransformerTest.kt

Trello [442](https://trello.com/c/RQVOzssn/442-add-audience-field-to-course-model-api) Add audience field to course model API
Extended tests to show presence of 'audience' property of CourseEntity, Added audience field to api, domain and CourseEntity transformer.

422 Add "audience" field to Course model (API)

---

.circleci/config.yml
doc/adr/0002-use-playwright-for-end-to-end-tests.md

[Trello card](https://trello.com/c/zGaYc1r5/415-add-e2e-tests)
We now run end-to-end tests on CI.
This will run end-to-end tests on the deployed dev environment to ensure we're testing the entire end-to-end journey with a real front and back end to catch anything that might break functionality.
The script clones the e2e test repo locally, installs dependencies and runs the Playwright test script.
This PR also adds an ADR to document our decision to use Playwright for our tests.

(415) Run E2E tests on CI

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/transformer/Transformers.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/CourseServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/transformer/TransformerTest.kt

Trello [465 API: fix failing Pact tests](https://trello.com/c/jcc6cAsa/465-api-fix-failing-pact-tests)
`PactContractTest` enabled, model and data tweaked to comply with current state of the Pact contract for this API.

Fix failing Pact tests

---

helm_deploy/hmpps-accredited-programmes-api/values.yaml

Trello: [417 Create Database](https://trello.com/c/kUnIVhHw/417-create-database)
Dev deployment fails due to Helm chart misconfiguration. 
Fix the Helm deployment by updating `vaules.yml` to use the correct name for the Kubernetes secret that contains the PostgreSQL Database credentials.

:bug: Helm deployment: Use the correct name for the kubernetes database credentials secret

---

Dockerfile

Added 
```
RUN mkdir /home/appuser/.postgresql \
&& curl https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem \
> /home/appuser/.postgresql/root.crt
```
to the `Dockerfile`.  The PostgreSQL driver should now trust the AWS RDS PostgreSQL instance to which it connects.

417 :bug: Add the current AWS RDS root certificate to the Java trust store when building the Docker image.

---

build.gradle.kts
helm_deploy/hmpps-accredited-programmes-api/values.yaml
helm_deploy/values-dev.yaml

https://trello.com/c/jZYDnjEO/395-add-sentry-to-ui-and-api-for-logging-errors
Adds and configures Sentry via the Spring Boot SDK following instructions here: https://ministryofjustice.sentry.io/projects/hmpps-approved-premises-api-k1/getting-started/
I've added the new `SENTRY_DSN` environment variable as a Kubernetes secret so this should hopefully deploy successfully.

(395) Add Sentry spring boot SDK and configuration

---

.circleci/config.yml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

https://trello.com/c/CWoUr4XC/444-create-prod-pre-prod-environments
- Adds environment variables to be used in Sentry for filtering issues based on the deployed environment
- Adds deployment steps to CircleCI script for prod and pre-prod environments.

(444) Add prod and pre-prod deployment config

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/PactContractTest.kt
src/test/resources/db/migration/R__test_data.sql

[503-add-new-pact-provider-test-for-a-single-offering
](https://trello.com/c/GTnZa5qw/503-add-new-pact-provider-test-for-a-single-offering)
Adds a new Pact state to cover requests made for an individual offering with id `20f3abc8-dd92-43ae-b88e-5797a0ad3f4b`

(503) Add pact provider test for a single offering

---

docker-compose.yml

Update docker-compose.yml:
* api container waits for postgresql instance to become available before starting.
* Database is empty because this is using a production image.
* Db can be populated from `R_test_data.sql` using intelliJ or the postgres command line tools available in the running container.

Improve docker-compose.yml configuration.

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

When testing out the preprod environment, I noticed the API doesn't appear to be accessible on the web, despite the service successfully running on a Kubernetes pod.
I believe the reason for this is the incorrect `host` and `tlsConfig` values we're setting for each environment, which have been wrong since the initial setup - we had an erroneous `hmpps-` prefix and a missing `tlsSecret` field here.
These values now match those specified in the Cloud Platform Environments repository:
- [Prod](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/06-certificates.yaml)
- [Preprod](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.se …

Add correct host and tlsconfig for Prod and Preprod

---

helm_deploy/values-prod.yaml

Indents incorrectly-indented env values in `values-prod` - hopefully this will fix our deployments.
There was no notification of this error, other than the pods failing to start!

Indent prod env YAML values

---

docker-compose.yml
src/main/resources/application-seed.yml
src/main/resources/seed/db/migration/R__Seed_Data.sql

Trello: [529 Seed local dev database](https://trello.com/c/n2CpKiCa/529-seed-local-dev-database)
The seed profile is defined by application-seed.yml. Seed data is loaded into the database using a flyway repeatable migration at src/main/resources/seed/db/migration/R__Seed_Data.sql and finally, the docker compose configuration file docker-compose.yml has been updated to launch the hmpps-accredited-programmes-api image container with the seed profile enabled. This means that application can be started and populated with seed data using 'docker-compose up'.
* Introduced a new Spring Boot profile 'seed' defined in `application-seed.yml` 
* The profile instructs flyway to run migrations from `classpath:/seed/db/migration/` in addition to the standard location
* The migration script, …

Add a Spring Boot profile 'seed' that loads seed data into the appliation's database.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseServiceTest.kt

This PR is a follow-up to  [this PR (59)](https://github.com/ministryofjustice/hmpps-accredited-programmes-api/pull/60). It:
* Contains minor corrections and improvements to the documentation contained in the OpenApi spec at `api.yml`
* Extends the scope of the response body for the offerings bulk upload (PUT /courses/offerings) to warn about rows that lack a value for the `contactEmail` field.
As described above. The first commit contains the open api documentation improvements, the second adds warning messages for offerings that lack a contactEmail.

2023 06 27 minor improvements

---

script/upload_csv_dev

Trello [285 Import existing programmes to API (dev)](https://trello.com/c/V8I5z5XN/285-import-existing-programmes-to-api-dev-env)
New script `upload_csv_dev` PUTs CSV format files to the API bulk upload end-points.  
Data in the API is replaced by that in the CSV files.

(285) Add script to populate the 'dev' environment with programmes data

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/NewCourse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/transformer/Transformers.kt
src/main/resources/db/migration/V7__add_course_identifier.sql
src/main/resources/seed/db/migration/R__Seed_Data.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/inmemoryrepo/InMemoryCourseRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/CourseAudienceRelationshipTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/CourseEntityRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/JpaCourseRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CsvHttpMessageConverterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CsvTestData.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/transformer/TransformerTest.kt

Trello [553 Modify bulk course upload to store course `identifier` in the database](https://trello.com/c/saKu5vkd/553-modify-bulk-course-upload-to-store-course-identifier-in-the-database)
Introduced an `identifier` column to the `course` table and an identifier column to the `PUT /courses end-point `used for bulk upload of course data from a CSV file.  Modified the code so that the identifier values in the uploaded CSV are stored in the `course.identifier` column in the db.

533 Add identifier to course

---

build.gradle.kts

https://trello.com/c/U0gghZBi/563-fix-api-pact-issue
We're currently seeing builds failing when tagging a Pact version on `main` due to the deployed version not being published.
I'm not 100% sure if this is the culprit, but this commit was the first one in which the `main` build started to fail, so I wanted to check this first.
This reverts junit5spring back down to 4.6.1 to see if this fixes the issue or changes anything.

Revert junit5spring to 4.6.0

---

build.gradle.kts

Reverts ministryofjustice/hmpps-accredited-programmes-api#71
Downgrading to 4.6.0 didn't fix our issue.

Revert "Revert junit5spring to 4.6.0"

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/PactContractTest.kt

https://trello.com/c/U0gghZBi/563-fix-api-pact-issue
Re-enables disabled Pact tests that were turned off to help speed up development.
Now that we have a more stable `dev` environment, this should help us catch any breaking changes.

Re-enable disabled Pact tests

---

.circleci/config.yml

We're currently notifying the dev channel for releases, but a more dedicated events channel for error and deployment notifications feels more appropriate and will keep the dev channel a more focused place for discussion etc.
Changes the channel for notifications to `#accredited-programmes-events`

Use accredited-programmes-events slack channel for releases

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/JpaCourseRepository.kt
src/main/resources/application.yml

Invoking some api end-points results in Hibernate running 'N+1' queries to populate courses with their `audiences` and `prerequisites` collections.  Although the datasets are small this is still inefficient and is easily fixed.
* Disable the Spring JPA 'open session in view' setting. 
* Set the fetch type for course.prerequisites, course.offerings and course.audiences to `FetchType.SUBSELECT `
* Selectively initialise collections in `JpaCourseRepository`

Eliminate inefficient Hibernate N+1 queries

---

.github/workflows/codeql.yml
build.gradle.kts

The build was failing due to an out of memory error.
Increase the amount of memory allocated to Kotlin compilation.

Fix memory issue on CodeQL build

---

helm_deploy/hmpps-accredited-programmes-api/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/HmppsAccreditedProgrammesApiExceptionHandler.kt

https://trello.com/c/QsqGgSG6/558-check-api-is-logging-errors-to-sentry
We currently use Sentry on the Frontend to log errors and send a slack notification to the events channel. Although we do get some error handling in ApplicationInsights, this doesn't notify us in the same way.
- Configures the API to log any unexpected exceptions to Sentry
- Sets Sentry sample rate
The Sentry team recommend sampling your transactions for two reasons:
- Capturing a single trace involves minimal overhead, but capturing traces for every page load or every API request may add an undesirable load to your system.
- Enabling sampling allows you to better manage the number of events sent to Sentry, so you can tailor your volume to your organization's needs.
[Release process …

(558) Configure sentry

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/HmppsAccreditedProgrammesApiExceptionHandler.kt
src/main/resources/logback-spring.xml

Trello [558 Check API is logging errors](https://trello.com/c/QsqGgSG6/558-check-api-is-logging-errors-to-sentry)
Use a version of the Sentry API that is compatible with Spring Boot 3.
Log uncaught `Throwable`s, not just `Exception`s.
Add a Sentry logging appender to the Logback configuration in `logback-spring.xml`
Prior to deploying to prod/preprod the Sentry DSN that is stored in the Kubernetes secrets for the API should be changed. Currently the API DSN is the same as the one used by the UI.  This is incorrect. There is a separate DSN for the API which can be obtained from the Sentry console.  This value should be replace the current value found in the kubernetes API secrets.
Update: DSNs have been corrected in dev, preprod and prod environments.

Fix Sentry installation and logging.

---

build.gradle.kts

Updated Gradle plugin dependency 'uk.gov.justice.hmpps.gradle-spring-boot' to version 5.2.4 to remove vulnerabilities  CVE-2023-3635, CVE-2023-34036

Housekeeping: Bump plugin version to remove vulnerable dependencies from build

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/MutableCourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/AudienceRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/CourseEntityRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/JpaCourseRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/InMemoryCourseRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/InMemoryCourseRepositoryTest.kt

Trello: [Remove/simplify `InMemoryCourseRepository` in the API](https://trello.com/c/vdftAilZ/618-remove-simplify-inmemorycourserepository-in-the-api)
This PR contains a refactoring.  The application's functionality does not change.
The application initially implemented a read-only API. The domain model from which the API responses were constructed relied on a domain model containing instances of `CourseEntity`, `Offering` and `Prerequisite` classes. These entities were retrieved from a `CourseRepository`, an interface initially implemented wholly in memory as `InMemoryCourseRepository`.
Further development introduced a database as a long term store for these entities and a `JpaCourseRepository` implementation of `CourseRepository` as the replacement for `InMemoryCourseRepository`. …

Refactor: Simplify Repository code

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/jparepo/CourseEntityRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/jparepo/JpaCourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/OfferingsController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/jparepo/CourseEntityRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/OfferingsControllerTest.kt

Trello: [687 Add a GET course y offering id endpoint](https://trello.com/c/HQjspnDx/687-add-offerings-offeringid-course-endpoint)
* Added `GET /offerings/{offeringId}/course` endpoint to OpenApi definition
* Created method `findByOfferings_id` on the `CourseEntityRepository` class
* Provided an implementation of the new endpoint  in a new class `OfferingsController` 
* Fixed a message layout and improved `CourseController` tests

687 add get course by offering id endpoint

---

build.gradle.kts
helm_deploy/hmpps-accredited-programmes-api/Chart.yaml

Updates to code and Helm chart dependencies to satisfy reports from renovate bot.
* HMPPS Spring Boot plugin 5.2.4 updated to 5.3.0
* Sentry 6.25.2 updated  to 6.28.0
* Google Guava  32.1.1-jre updated to 32.1.2-jre
* generic-service 2.6.3 updated to 2.6.4

2023 08 15 housekeping

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralsController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralsControllerTest.kt

Fixing response code bug spotted by Ynda.
A successful invocation of the `POST /referrals` endpoint now returns HTTP status code 201 (Created). 
Previously it returned 200 (Ok).

:bug: A successful invocation of the `POST /referrals` endpoint should return HTTP status code 201 not 200.

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Responding to prompts from Renovate Bot.
Updated Gradle to v8.3
Updated Gradle buildfile to remove use of deprecated property `buildDir`
Updated Gradle build file dependencies

Housekeeping: Version updates (Gradle and dependencies)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/HmppsAccreditedProgrammesApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/domain/Referral.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/domain/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/domain/ReferralsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/transformer/Transformers.kt
src/main/resources/db/migration/V11__extend_referral_table.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/domain/ReferralStatusTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralsControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/transformer/TransformersTest.kt

* Trello: [Add PUT `/referral/{referralId} endpoint](https://trello.com/c/66GNllNO/705-add-update-referral-put-endpoint-api)
* Trello: [Add PUT /referrla/{referralId}/status` endpoint](https://trello.com/c/SGdEhubR/746-add-referrals-id-submit-endpoint-to-mark-a-referral-as-submitted-true-api)
A `Referral` resource holds information about a referral.  Over time the `Referral`'s status will change and it will acquire management information about the referral, its assessment and participation in a course offering.
Additional endpoints are required to enable clients to update the referral itself and to update its status.
* Added new endpoint definitions to `api.yml` for `PUT /referrals/{referralId}` and `PUT /referrals/{referralId}/status`
* Implemented the endpoint behaviour
* Minor renaming …

Extend API to enable updates to a Referral

---

.github/workflows/codeql.yml
build.gradle.kts
helm_deploy/hmpps-accredited-programmes-api/Chart.yaml

Renovate bot  commits branches with recommended dependency updates. 
This PR adds those updates to the main branch.
* build.gradle.kts updates. KoTest 5.6.2 -> 5.7.2, sentry 6.28.0 -> 6.29.0
* Helm chart dependency updates. generic-prometheus-alerts 1.3.2 -> 1.3.3
* Github workflow dependency updates (actions/checkout@v3 -> actions/checkout@v4)

Dependency updates

---

build.gradle.kts

The most recent automated OWASP dependency check recommended an update  of the Gradle HMPPS `gradle-spring-boot` plugin.
Plugin `uk.gov.justice.hmpps.gradle-spring-boot` updated from 5.4.0 to 5.4.1

Update hmpps gradle-spring-boot plugin.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/NewCourse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/transformer/Transformers.kt
src/main/resources/db/migration/V13__add_referable_boolean_to_course.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/MockkMatchers.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/jparepo/OfferingRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/InMemoryCourseRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/transformer/TransformerTest.kt

> [see ticket #677 on the Accredited Programmes Trello board.](https://trello.com/c/EaDLACLz/677-add-referable-property-to-course-api)
We needed a new boolean value for determining whether users can refer people onto various course offerings.
Rather than include this as a property of `Offering`, I have added the new `referable` field to `Course`, which defaults to `true`.

677 add referable property to course

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesIntegrationTest.kt

> [see ticket #779 on the Accredited Programmes Trello board.](https://trello.com/c/fYmioX3S/779-remove-old-courses-courseid-offerings-offeringid-endpoint-api)
We previously used a slightly unintuitive way to access course offerings via the API, using an essentially nested endpoint of `/courses/:courseId/offerings/:offeringId`. [We recently implemented an `/offerings/:offeringId endpoint` in #718](https://trello.com/c/yxmFMhl9/718-add-offerings-id-endpoint-api-ui), which the UI is now using. Therefore, we can now safely remove the old endpoint and associated tests, which are essentially duplicates.

779 Remove old courses/{courseId}/offerings/{offeringId} endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/Offering.kt
src/main/resources/db/migration/V14__add_withdrawn_to_offering.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/jparepo/OfferingRepositoryTest.kt

Trello: [Update Courses, Prerequisites, Offerings instead of replacing](https://trello.com/c/sooyolH2/614-add-scripts-for-updating-course-offering-data-in-the-service)
* Added a `withdrawn` property to `Offering`
* Exclude withdrawn `Offering`s from course offering resources

614 add soft delete for offerings

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/OfferingUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/transformer/Transformers.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CsvTestData.kt

Currently the only way to update Courses, Offerings, Prerequistes etc is using the bulk update mechanism.
This consists of POSTing CSV files to the `PUT /courses`, `PUT /offerings` and `PUT /prerequisites` endpoints.
Before this PR Offerings were updated by:
* Deleting all offerings
* Inserting an Offering for each valid record in the uploaded offerings CSV file.
This becomes a problem when referrals are linked to offerings because replacing an Offering changes the Offering's ID.
The solution is to add a soft delete option to Offerings (done) and then update Offerings in place.
Matches are determined by Course identifier and OrganistionId (PrisonId).
This is what happens when a set of offering records is uploaded:
* The new offerings are grouped by CourseId.
* The current offerings and …

614 update offerings instead of replacing

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationHistoryController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationHistoryControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationHistoryIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleControllerTest.kt

https://trello.com/c/n7qRBIHo/865-tweak-course-participation-endpoints
This tweaks the endpoints used for fetching course participations slightly to the following for ease of use on the frontend:
```
GET all by person: /people/:prisonNumber/course-participations
POST one /course-participations
GET one /course-participations/:courseParticipationId
PUT one /course-participations/:courseParticipationId
DELETE one /course-participations/:courseParticipationId
```
In doing this, OpenAPI has generated a new controller for us, so the endpoint for fetching `courseParticipations` has now been moved to its own `PeopleController`.
Once this is done, and Nick's refactoring PR is in, I'd like to rename these entities slightly.
As part …

(865) Tweak course participation endpoints

---

doc/how-to/replace-all-api-data.md
script/kubernetes-scripts/download-csvs
script/kubernetes-scripts/upload-csvs
script/local-scripts/README.md
script/local-scripts/all-courses-csv
script/local-scripts/all-offerings-csv
script/local-scripts/all-prereq-csv
script/local-scripts/put-courses
script/local-scripts/put-offerings
script/local-scripts/put-prereq
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/jparepo/JpaCourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CsvHttpMessageConverter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/OfferingsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/transformer/Transformers.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CoursesIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CsvHttpMessageConverterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/CsvTestData.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/restapi/OfferingsControllerTest.kt

Trello: 
* [Add scripts for updating course data](https://trello.com/c/sooyolH2/614-add-scripts-for-updating-course-offering-data-in-the-service)
* [Mark non-referrable courses as non-referrable](https://trello.com/c/DygFUaSW/837-mark-non-referable-courses-as-non-referable-api)
The API contains PUT endpoints for bulk add/update/delete operations on Courses, Offerings, Audience and Prerequisites.
This PR adds corresponding GET endpoints for downloading a CSV format representation of Courses, Offerings, Audience and Prerequisites.  The documents from these endpoints are compatible with their corresponding PUT endpoints so that the data can be round-tripped.  
These bulk downloads may be saved as CSV format files and modified in spreadsheet editing programmes such as Microsoft Excel or …

614 add bulk csv download endpoints for round trips

---

README.md

The swagger URL in the README was pointing to the incorrect location (a prefixed `hmpps` in the URL).
Updates swagger URL to point to the correct location.

Fix swagger url

---

build.gradle.kts

The Gradle OWAP dependencyAnalyze task suggests updating a couple of dependencies.
Updated a couple of dependencies in `build.gradle.kts`

Housekeeping: Bump dependencies

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/Transformers.kt
src/main/resources/db/migration/V18__extend_course_participation_table.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/testsupport/RandomDataGenerators.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/testsupport/RandomDataGeneratorsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/OfferingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/ReferralEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/repositories/JpaCourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleControllerTest.kt

Trello: [Add additional programme history fields to API](https://trello.com/c/kWwW6vM1/862-add-additional-programme-history-fields-to-api)
Expanded the `setting` and `outcome` properties of `CourseParticipation`
* `yearStarted` has been moved to `outcome`, see below
* `setting` now has `var location: String?` and `var type: CourseSetting`
* `outcome` now has additional properties `var yearStarted: Year?` and `var yearCompleted`: Year?`
`outcome` has an additional unused private field
```
@Formula("0")
val ignoreMe: Int = 0
```
If all properties of an `@Embedded` object are `null` Hibernate will not create the object. Instead the property (`outcome`) is set `null` - even if it is not a nullable type! The additional non-nullable field `ignoreMe`,  forces Hibernate to populate the `outcome` …

(862) Add additional programme history fields to API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/jpa/ExtraJpaConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/Transformers.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/jpa/RepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/restapi/JwtAuthHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/testsupport/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/repositories/JpaCourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleControllerTest.kt

Trello: [Add additional programme history fields to API](https://trello.com/c/kWwW6vM1/862-add-additional-programme-history-fields-to-api)
The card asks for an `addedBy` (required) text field (name/username?)  and a `createdAt` field to be added to programme history records returned from the API.
This is achieved by 
* Enabling JPA Auditing
* Adding an implementation of the `AuditorAware` interface. The implementation obtains a username from the Spring Security SecurityContext.  The Spring Security implementation extracts this username from the JWT token provided with the request.
* Adding `@EntityListeners(AuditingEntityListener::class` to the `CourseParticipation` to make it auditing aware
* Adding audit properties annotated with `@CreatedBy`,` @CreatedDate`, `@LastModifiedBy` and …

862 Course participation audit fields - second step - manual rebase

---

build.gradle.kts

`sentryVersion` for Gradle managed dependency  ` implementation("io.sentry:sentry-spring-boot-starter-jakarta:$sentryVersion")` changed from `6.29.0` to `6.30.0`

Bump Sentry version to remove a vulnerability.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/domain/Referral.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/domain/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralsController.kt
src/main/resources/db/migration/V19__add_has_reviewed_programme_history_to_referral.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/ReferralEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/repositories/JpaReferralRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralsControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/referral/restapi/ReferralsIntegrationTest.kt

Trello: [Add additional programme history fields to API](https://trello.com/c/kWwW6vM1/862-add-additional-programme-history-fields-to-api)
Added a new, mandatory, boolean field hasReviewedProgrammeHistory to the data exchanged over api endpoints for referrals.  Field is propagated to database and returned in queries.

862 Add property hasReviewedProgrammeHistory to Referral

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/Transformers.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationIntegrationTest.kt

There's a requirement for creating Course Participation entries with very little information.
This PR makes a small change and adds a test to shows how this can be done.
* Make the 'type' field of CreateCourseParticipation.setting nullable (optional).
* Propagate this through the application.
* Added an integration test to `CourseParticipationIntegrationTest` to show that the scenario works correctly.

Add an integration test that confirms that a course participation having minimal fields set can be persisted and retrieved.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/Transformers.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/repositories/JpaCourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleControllerTest.kt

>see #137 and [#953 on the Accredited Programmes Trello board.](https://trello.com/c/FKoplgky/953-separate-out-detail-field-from-outcome-on-courseparticipation)
This PR follows on from #137's migration of the `detail` field from within the `CourseOutcome` embedded object to the top-level `CourseParticipation`, due to a refinement of requirements which decouples course participation details from the outcome of that course - namely by removing the now-deprecated original field.
Associated unit and integration tests are similarly updated.

953 Remove deprecated `detail` attribute from CourseParticipation 2/2

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipation.kt

This is a tiny housekeeping fix which snuck through the PRs to remove legacy `detail` from the `CourseParticipation`.`CourseOutcome` domain object.
- removes `detail` from `CourseParticipation`.`CourseOutcome`

Fix: remove `detail` from CourseParticipation.CourseOutcome domain object

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/Transformers.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/repositories/JpaCourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleControllerTest.kt

> [see #944 on the Accredited Programmes Trello board.](https://trello.com/c/Vtpg6D7G/944-make-setting-and-outcome-not-required-on-a-courseparticipation-make-type-status-required-api-s)
We [recently](https://github.com/ministryofjustice/hmpps-accredited-programmes-api/pull/133) updated the API to accept an empty object when creating a `CourseParticipation`. Manually submitting its empty embedded objects on creation -`CourseParticipationSetting` and `CourseOutcome` - now seems redundant.
This ticket focuses on removing these as required fields in the OpenApi specification, when `POST`ing to `/course-participations`:
- Removing the `required` flag from `setting` on `CourseParticipation`, and giving the `type` enum property on `CourseParticipationSetting` the `required` flag instead.
- …

944 Make CourseParticipation`setting` and `outcome` fields optional

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/Transformers.kt
src/main/resources/db/migration/V21__add_course_name_to_course_participation.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/domain/CourseParticipationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/repositories/JpaCourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleControllerTest.kt

> [see #874 on theAccredited Programmes Trello board.](https://trello.com/c/xWq77vNY/874-add-coursename-field-to-courseparticipation-api-m)
We currently store a `courseId` of an existing course in our service or `otherName` field on a `CourseParticipation`.
Given that `CourseParticipation` is (currently) used to represent courses that a person in prison may have attended that predate courses recorded in our service, it doesn’t feel right to store a `courseId` against it.
This PR adds a `courseName` field in place of these other two fields, whilst maintaining backwards-compatibility.

874 Add `courseName` to `CourseParticipation`

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/restapi/JwtAuthHelper.kt

Updating the version of the `io.jsonwebtoken` application dependency  produced compile time warnings in `JwtAuthHelper`.
This PR eliminates those warnings.

Fix deprecation warnings in JwtAuthHelper

---

.gitignore
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseParticipationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/update/CourseParticipationUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/CourseParticipationTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseParticipationService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseParticipationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/JpaCourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseParticipationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/PeopleControllerTest.kt

https://trello.com/c/8EEamFWG
No env variables needed
No change to architecture. No ADR required
Remove deprecated fields courseId and otherCourseParticipation. Now that we are using a `name` instead of these fields, we have removed these fields. 

973 remove course id and other course name from course participation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseControllerTest.kt

> see [#958 on the Accredited Programmes Trello board.](https://trello.com/c/ZbZb6IUc/958-add-course-names-endpoint)
The current way in which course names are retrieved do not account for duplicate named results. Whilst the front-end could feasibly deal with each individual request dynamically, by filtering the response from the standard `/courses/` endpoint, we felt it was more prudent to enshrine this sort of filtering functionality in the back-end, in preparation for (and therefore to remain consistent with) later planned tickets for filtering, sorting, and pagination.
In this case, rather than define a `/course-names` endpoint, which would have the OpenApi generator define an entirely new `CourseNamesController` flow, I have implemented this new endpoint under the existing `/courses/` …

#958 Add new `courses/course-names` endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseParticipationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/CourseParticipationTransformers.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseParticipationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/CourseParticipationTransformersTest.kt

> [see #957 on the Accredited Programmes Trello board.](https://trello.com/c/gJxNNdoy/957-ensure-were-validating-courseparticipation-years-on-the-api-api)
We're kicking off the validation of entities in the API with this branch. This one focuses on the `Year`-type fields in `CourseParticipationEntity`.`CourseParticipationOutcome` - `yearStarted` and `yearCompleted`.
- Created a new `Year`.`isOrAfter(base: Year)` function to be used to check if `Year`-type fields are within a range, using Kotlin's `rangeTo/..` implementation.
- Edited the `CourseParticipationTransformer` to throw `ValidationException`s when the two `Year`-type fields contain values that are before a particular year. (As it stands currently, the `base` for these fields is 1990, as that's the earliest timeline we have for …

#957 validate course participation years

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/update/ReferralUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V23__migrate_referral_reason_to_additional_information.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/ReferralTransformersTest.kt

> [see #1018 on the Accredited Programmes Trello board.](https://trello.com/c/x51DKI0K/1018-remove-legacy-referral-reason-field-in-the-data-model-and-api)
> [for further context, see #860 on the Accredited Programmes Trello board.](https://trello.com/c/ktEadiIa/860-rename-reason-field-to-additionalinformation-in-the-data-model-and-api)
This is the second part of the process to add a column called `additional_information` to the `referral` table.
The first part of this process added the new column and marked its legacy counterpart, `reason`, as deprecated. The associated PR is #152.
- add new Flyway migration to migrate any stored information from `referral.reason` to `referral.additional_information` (giving precedence to the latest changes to either column), then delete …

#1018 remove legacy reason referral

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V24__add_submitted_on_to_referral.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/RandomDataGenerators.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/resources/db/migration/R__test_data.sql

> [see #1033 on the Accredited Programmes Trello board.](https://trello.com/c/052kKyeR/1033-add-post-referrals-id-submit-endpoint-and-submittedat-field-to-referral-model)
- added a new `submittedOn` property to `ReferralEntity`.
- exposed a new POST endpoint for submitting a referral at `/referrals/{id}/submit`, which changes `status` to `REFERRAL_SUBMITTED` and `submittedOn` to `LocalDateTime.now()`
- added minimal but functional validation to check a referral isn't already submitted.
- updated unit and integration tests.
- updated pact tests (with Anand's assistance).

1033 submit referral

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/JpaReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/CourseParticipationTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseParticipationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/ReferralTransformersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/db/migration/R__test_data.sql

https://trello.com/c/vEOIj7KP/1045-build-endpoint-for-returning-an-organisations-referrals-containing-only-data-in-our-service-l

1045 endpoint for returning an organisations referrals only from db

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/ReferralRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

> [see ticket #1048 on the Accredited Programmes Trello board.](https://trello.com/c/8sm2MfBU/1048-implement-pagination-for-the-caselist-endpoint-m)
- Updated the OpenApi specification to have the `ReferralController` return a paginated version of the usual list of `ReferralSummary` objects. The UI can now call the back-end at, e.g., `/referrals/organisation/{organisationId}/dashboard?page=0&size=3`, to return paginated responses.
- Implemented pagination in the `ReferralRepository`, which makes use of Spring Data JPA's inbuilt paging and sorting.
- Updated unit and integration tests for the referral control flow.
ready to be released once …

#1048 Implemented pagination across the Referral control flow.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/read/ReferralSummaryProjection.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V24__add_submitted_on_to_referral.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralSummaryProjectionFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/ReferralRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/ReferralTransformersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/db/migration/R__test_data.sql

[> see #1087 on the Accredited Programmed Trello Board.](https://trello.com/c/HeepPzY6/1087-add-submittedon-date-coursename-and-audience-to-dashboard-endpoints-m)
Several new requirements for the structure of a returned referral summary were introduced in this ticket, including adding mandatory fields from other tables: `submittedOn` from `referral`, `courseName` from `course`, and `audiences` from the many-to-many relationship in `course` and `audience` (we have a join table `course_audience` for this). This necessitated editing the existing `ReferralRepository` queries to retrieve the correct information, so it felt prudent in this case to define this more complex data set as a JPA projection in a separate Data Transfer Object (`ReferralSummaryProjection`). This also necessitated …

#1087 Add & edit fields for data returned from caselist endpoint.

---

src/main/resources/seed/db/migration/R__Seed_Data.sql

This will help in local development as we move to restricting submitted referral pages to submitted referrals (we'll want a seeded referral we can easily open up)
I've added in the same fields as set in `R__test_data.sql`
We're moving to restrict submitted referral pages so that you can't view a draft referral's details via them
- Add seeded submitted referral for use in UI locally

(1057-adjacent) Add seeded submitted referral

---

src/main/resources/seed/db/migration/R__Seed_Data.sql

In a recent commit, I attempted to add an extra seeded referral, but I left a semi-colon at the end of the line adding the first seeded referral where there should now be a comma

Fix seed data SQL

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/projection/ReferralSummaryProjection.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralSummaryProjectionFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

> [See #996 on the Accredited Programmes Trello board.](https://trello.com/c/b6nK2Ryc/996-add-filtering-for-caselist-endpoint-m)
We wanted to apply filtering to the various referral summaries a user would retrieve from the db - namely, for `audience` and `status` aspects of referrals. As with pagination, this is applied across the controller layer, meaning that any subsequent changes to the underlying shape of the data - e.g. when implementing data retrieved from calls to other APIs - should have a negligible effect upon the logic used to filter results.
- Added filtering to the referral endpoint for `audience`, `status`, and `courseName` which may be used in any combination.
- Updated unit testing to reflect this flexibility with several `@ParameterizedTest`s.
- Updated integration …

#996 Filtering by `audience`, `status`, and `courseName` for the caselist endpoint (only internal API data for now)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OrganisationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/OrganisationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

https://trello.com/c/w2RX414a/1166-add-route-for-fetching-all-courses-for-an-organisation-m
Fetches all courses based on organisation id

1166 add route for fetching all courses for an organisation

---

.circleci/config.yml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

https://trello.com/c/3n25jR0i/775-restrict-the-service-to-ips-in-preprod-and-prod-m
For security, we should have our preprod and prod environments to whitelisted IP addresses, so they're available to users at the MOJ and in prisons.
This restricts access to the site to IPs in the following groups:
- Internal
- Prisons
- Private prisons
The IPs are listed in [a config file in another repo](https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml), then published as environment variables in the `hmpps-common-vars` CircleCI context. These are fetched in the `deploy_env` job in CircleCI.
Once this is merged, we'll need to use the MOJ VPN to access these environments.
**N.B** Before merging, we'll need to investigate how this will affect our monitoring with …

(775) Restrict preprod and prod to HMPPS group IPs

---

.github/workflows/git.yml

There's currently a risk of fixup commits getting merged
Add workflow to check commit messages to ensure there are no `fixup!` and `squash!` commits before merging to `main`
Squash commits will only be noted in the failing workflow step if there are no fixup commits - the workflow appears to exit early if fixup commits are found
Per UI: https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/commit/7cf05806649879a1e32fc144f6390bddba29e4fb

Add workflow to check commit messages

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt

We've added a PR in the UI codebase for being able to view the assess case list separated by course name.
This adds missing states added in [this UI PR](https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/pull/384) which should ensure all our pacts continue to pass.

Add Pact provider states for course filtering

---

.circleci/config.yml
README.md

We disabled our E2E tests a while ago to speed up development while the Find journey was changing regularly.
- Turns on E2E tests as part of the build process to ensure deployments don't break things.
- Updates README formatting and corrects a couple of errors.

Update README & turn on e2e tests

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseParticipationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferrerUserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/projection/ReferralSummaryProjection.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferrerUserRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V25__create_user_table.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/JwtAuthHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseParticipationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralSummaryProjectionFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferrerUserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/JpaCourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/ReferralRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/RepositoryTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseParticipationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/PeopleControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/ReferralTransformersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/db/migration/R__test_data.sql

[> see #1122 on the Accredited Programmes Trello board.](https://trello.com/c/gulvnZLL/1122-add-new-user-model-and-link-to-referrals-to-replace-referrerid-l)
A requirement for R&M is that a user can see specifically all referrals they have made, not just their organisation. Given this, we needed to represent users in our data structures. Currently we only use an API-generated referrerId when creating new referrals, which is no longer sufficient.
This PR introduces the usage of Spring Security's `SecurityContextHolder` to retrieve the username and role of the current logged-in user. This is used for creating a referral, and is persisted in its own table as `ReferrerUser`, named as such to allow scope for building other types of user (also, `user` is a protected keyword in all SQL dialects, …

#1122 Implement new ReferrerUser entity and update Referrer accordingly.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

>[ see #1191 on the Refer & Monitor Trello Board.](https://trello.com/c/EzGOp4bf/1191-allow-list-of-status-values-for-dashboard-endpoint)
This PR extends the functionality of our caselist GET request to allow a list of `ReferralStatus` values. Spring dynamically reads in a comma-separated string as a list, so this can be sent through easily, e.g.:
```
/referrals/organisation/$organisationId/dashboard&status=referral_started,referral_submitted
```
will return `ReferralSummary` objects filtered to include those with either status.

#1191 Allow list of status values for caselist dashboard endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V26__retire_referrerId.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonSearchApi/PrisonerSearchApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/RandomDataGenerators.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralSummaryBuilderServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/ReferralRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/ReferralTransformersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/db/migration/R__test_data.sql

> [see #1200 on the Refer & Monitor Trello board.](https://trello.com/c/WMr6ClIF/1200-gracefully-retire-referrerid-in-favour-of-novel-referreruser-and-username-retrieval-from-the-fe-token)
Following from #185 which added a new `ReferrerUser` which sources its information from the current logged-in user in place of the original `referrerId` implementation, this PR gracefully retires it.

#1200 Retire referrerId from the Referral control flow

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralSummaryBuilderService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonSearchApi/PrisonSearchApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralSummaryBuilderServiceTest.kt

> [see #1205 on the Accredited Programmes Trello board.](https://trello.com/c/r6Hy20fA/1205-return-earliest-release-date-from-api-m)
We currently fetch the following fields from the Prisoner Search:
- Tariff date
- Parole eligibility date
- Conditional release date
- Indeterminate sentence
This PR implements `getEarliestReleaseDate` which determines the earliest possible release date for a particular individual. This is required for the user-caselist view in the UI.
This has been handled by introducing a boolean in `ReferralSummaryBuilderService` which will optionally produce the `ReferralSummary` object with the additional field `earliestReleaseDate`. This is open for extension and modification, in the case that different information is required for building a `ReferralSummary` object. …

#1205 Implement getEarliestReleaseDate for caselist ReferralSummary objects

---

README.md

Add dependency update documentation to repo to inform new devs that vulnerabilities are often taken care of for us by other teams, and of the Renovate process.

Add dependency update documentation to repo

---

helm_deploy/hmpps-accredited-programmes-api/values.yaml
src/main/resources/application-local.yml
src/main/resources/application.yml

We had some issues setting up wiremock on the API side, which led to some confusion about how the different environments are configured, and led us to believe our setup wasn't as clear as it could be.
- Moves local application config into base `application.yml` where possible.
- Removes duplicate setting of env vars where not needed, instead leveraging Spring's environment variable naming convention
- Renames some environment variables to be a bit clearer, in line with the Approved Premises API team's naming convention.

Simplify `application.yml` and different environments

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

In https://github.com/ministryofjustice/hmpps-accredited-programmes-api/pull/220/commits/0a71b522742720a8fcae3b757ec0e753f88b2093, we simplified the environment variables, but forgot to update the variable names in the Helm deployment files. These need to match the values set in `application.yml` to successfully override them.
Adds missing prefix to set values correctly for integrations.

Add missing `SERVICES` prefix to env vars

---

docker-compose.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/BaseHMPPSClient.kt
src/main/resources/application.yml
wiremock/mappings/prisoner-search.json

When running the API via a Docker image, e.g. in the UI codebase, we weren't providing any responses for the values obtained from the Prisoner Search or Prison Register.
- Sets up mocks for the Prisoner Search API when running locally, matching the people in prison expected in the UI.
- Configures Docker container to use these mocks and the locally-running Prison Register when running the service with docker compose.

Add Prisoner Search mocks & local Prison Register response when running via Docker

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt

The `Referral(s) exist for the logged in user` test is currently failing due to our re-use of data between tests, which we urgently need to fix:
In `R__test_data.sql`, we create one Referral for `TEST_REFERRER_USER_1`. This is updated in tests to have a non-null `submittedOn` value. In another test, we create a new referral, which then has a null `submittedOn` value.
Pact [can't handle](https://github.com/pact-foundation/pact-js/issues/393) these two referrals having different types of their `submittedOn` values (specifically one being `null` and one a `string`), so the expectation fails.
Adds missing Pact states, even if this won't fix Pact completely at this moment in time.
Once we refactor our Pact tests to set up and tear down data in between tests, we'll be able to get the failing …

Add missing pact states

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt

Because we weren't stubbing the Prisoner Search here, we were getting back `null` values for all Prisoners returned. Pact was failing due to the consumer tests expecting these to be strings.
Provides a mocked response for the Prisoner Search endpoint in Pact tests to ensure we're always fetching realistic people in prison.
This also fixes some test constants, using Prison Numbers that match those found in the `test_data.sql` file. These are a bit messy at the moment and need tidying up, but that can come in a separate PR.

Stub Prisoner Search with Wiremock in Pact tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/model/Prisoner.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

We fetch names of people in prison from the Prisoner Search, which, according to the [Open API schema](https://prisoner-search-dev.prison.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/Prisoner) are required, so wouldn't be `null`.
Make `prisonNumber`, `firstName` and `lastName` fields required on a `ReferralSummary`.

Make `prisonNumber`, `firstName` and `lastName` fields required

---

README.md

134be24 updated the project to use Java 21, but the README section that describes how to install and select the Java version via IntelliJ IDEA still refers to Java 19
- Update README to reflect Java update re: IntelliJ usage (#219)

Update Java version for Intellij usage in README

---

doc/how-to/test-pact-locally.md

Pact contracts are published to the [Pact Broker](https://pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk/) on successful dev deployments. It's sometimes useful to be able to test against a local version of the contract, rather than having to push code to the dev environment and wait for the build to run every time.
Adds a `how-to` doc for running API Pact tests against a local copy of the UI's JSON specification, rather than the version published to the Pact Broker.

Add instructions for testing against local Pact contracts

---

.circleci/config.yml

https://trello.com/c/4fheMOjp/1275-api-build-owasp-failure-s-m
* add jdk_tag to circle ci config

add jdk_tag to fix owasp nightly failure

---

doc/adr/0007-store-names-sentence-dates-and-prison-names-in-our-database.md

https://trello.com/c/Oz7NfOxw/1304-write-adr-for-storing-of-prisoner-search-fields
Adds ADR to document our most recent decisions to store fields from external services in our own database to allow users to sort by them in their case lists.

(1304) Add ADR for storing external fields in our DB

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/config/SecurityConfiguration.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/JwtAuthHelper.kt

https://trello.com/c/AGDYXPvN/1085-add-role-guard-to-all-endpoints-on-api-m
Adding role ROLE_ACCREDITED_PROGRAMMES_API to secure all our endpoints

[1085] secure all endpoints with role ACCREDITED_PROGRAMMES_API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OfferingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/update/CourseUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/update/OfferingUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/db/migration/V28__add-referable-to-offering.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/CsvGenerators.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/OfferingEntityFactory.kt

> [see #1163 on the Accredited Programmes Trello board.](https://trello.com/c/86tT1mSV/1163-move-referable-property-from-course-to-offering-m)
This is the first of three PRs regarding the migration of the `referable` field from Course to Offering:
1. (this PR) add the new field to Offering and migrate any information from the old Course field to the new Offering field
2. (UI) read all referable information from the new Offering field
3. (API) retire Course.referable
Added referable field to Offering entity, updating all CSV, model and domain classes and functionality surrounding it.
Tests remain untouched, showing their integrity has been much improved after doing all those previous refactoring PRs!
As part of our …

#1163-1 Add referable field to Offering

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralSummaryBuilderService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt

https://trello.com/c/omP71TsY/799-add-a-new-audience-field-to-a-course-m

Deprecate audiences and add audience in referral summary

---

src/main/resources/static/api.yml

This PR should enable Swagger to send a JWT token allowing developers to use the swagger page to call APIs

Enable Auth for swagger try it now

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/update/CourseUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/db/migration/V30__retire_referable_from_course.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/CsvGenerators.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/RecordTransformersTest.kt

https://trello.com/c/vTrRy6WC/1306-remove-old-referable-field-from-course-entity-s
Add flyway migration to retire course.referable
Update OpenApi generator to remove deprecated referable field in API … 
Remove referable from entity-layer and associated factories
Update CSV generator to remove referable field from course-related st… 
Update transformers between Domain/API/Record to remove old referable… 
Update CourseService to remove old referable field

[1306] - remove referable from course entity

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/PersonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/PersonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralSummaryBuilderService.kt
src/main/resources/db/migration/V31__add_person_table.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PersonEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/simulations/__files/prison-search-results.json
src/test/resources/simulations/mappings/prison-search-api.json

We need to display a person in prison’s name and sentence dates in the “Refer” caselist and allow users to sort by these columns. Fetching and storing this in advance will allow us to make use of out-of-the-box sorting we’re currently doing with JPQL.
[1288](https://trello.com/c/pKRNcV1D/1288-fetch-and-store-person-in-prisons-details-when-creating-a-new-referral-m)

Store person details on referral creation

---

.circleci/config.yml

e2e tests on circleci have started failing due to new version.
Update from 1.39.0 to 1.41.1

Update playwright version to 1.41.1 for e2e tests on circleci 

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt

We store a Person’s name and sentence information on their Referral when a Referral is created. We need to update this regularly to ensure it doesn’t get out of date when the record is updated in upstream systems e.g. NOMIS.
The default API should NOT update the person. A parameter updatePerson=true shall be added to the endpoint which will carry out the update.
[1302](https://trello.com/c/IpxbwG3o/1302-fetch-and-update-person-in-prisons-details-when-viewing-a-referral-s)

Update local person details when a referral is selected

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/model/PrisonDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OrganisationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/OrganisationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V33__add_organisation_table.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/OrganisationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

https://trello.com/c/WvDsOYFf/1301-fetch-and-store-prison-name-when-creating-a-referral-m
* when a referral is created and the offering chosen has an organisation which doesn't already exist in our organisation table, then we create the organisation. 
* Organisation names don't change that often, so we don't update them on referral creation. (We could potentially have a cron job which does updates once a day)

[1301] - fetch and store prisonName when creating a referral

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/PersonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V34__add_referral_view.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

Added the ability to sort by any of the fields returned from the referal/view endpoints. Endpoints also paginate the results and provide filtering on certain fields. 
This is part one of the work. The second part will remove the existing referral summary endpoints making the code a lot cleaner.
[1135](https://trello.com/c/rRToX2Qr/1135-add-ability-to-sort-referrals-by-different-columns-m)

Added referral view endpoints

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

https://trello.com/c/WvDsOYFf/1301-fetch-and-store-prison-name-when-creating-a-referral-m
* We were using the wrong endpoint to fetch prison details and ended up storing duplicate prison details
* As part of this change, we are invoking a specific endpoint to fetch prison details

[1301] fix multiple organisastions from being created

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/PrisonerSearchApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/PrisonerSearchApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/model/Prisoner.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/PrisonSearchController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PrisonSearchIntegrationTest.kt
src/test/resources/simulations/__files/prison-search-results-match.json
src/test/resources/simulations/mappings/prison-search-api.json

Endpoint to allow searching for prisoners by prisoner number for a given caseload area. 
This is to enable the front end to move away from accessing external resources and to do this centrally via the AP backend. This will allow central auditing etc. 
[1348](https://trello.com/c/0inxW0I9/1348-prisonersearch-api-endpoint)

added prisoner search endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralStatusHistoryEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralStatusHistoryService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

Additional work to update the status history of the referral when the status is updated. 
This will update the end date time of the previous history record and record the duration and also create the new record assigning the previous status allowing us to (eventually) plot the referral journey and how long it took. 
[1344](https://trello.com/c/izfZWZG0/1344-referral-status-history-api)

update status history when assessment is submitted.

---

build.gradle.kts

version 6.2.2 has an issue which causes swagger to fail.

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralStatusHistoryService.kt
src/main/resources/db/migration/V44__Add_draft_closed_to_status.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

Added new flags to referral status reference data of draft and closed - this is to indicate that the status is a draft or a closed status (both false will mean open) 
This is so that the UI can filter on the three status groups without having to know what the statuses are. 

Added extra filters for open, closed and draft referrals

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusTransitionEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V45__Add_missing_status.sql
src/main/resources/db/migration/V46__status_transitions.sql
src/main/resources/db/migration/V47__populate_status_transitions.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

Added a simple workflow so that the next status of a referral can be sought depending on whether or not the user is a PT user. Also added validation to the existing update referral so that you can't change to an invalid status. 
Also added updatePerson flag to the status-history endpoint since this is now the entry point into viewing a referral
Trello --> [1401](https://trello.com/c/yoW6RGxe/1401-create-status-workflow)

added status transition workflow

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/StatusFlowDiagram.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

Added an endpoint to generate the markup for a status flow diagram:
the endpoint to generate the markup is /status-transition-diagram
paste the contents of the file into: http://magjac.com/graphviz-visual-editor/
or to generate an image save this as status_flow.dot
install graph viz: `brew install graphviz`
then run 
`dot -Tpng status_flow.dot -o status_flow.png `
to save the image

Added status flow diagram markup

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/EnabledOrganisation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/EnabledOrganisationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OrganisationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/EnabledOrganisationService.kt
src/main/resources/db/migration/V50__Add_enabled_organisation.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/AuditIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/EnabledOrganisationsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/EnabledOrganisationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/OrganisationControllerTest.kt

* Return list of pilot sites 
* new endpoint GET: /organisations/enabled
https://trello.com/c/Bfmu7X2p/1417-api-list-of-pilot-sites

1431 - Create new endpoint returning enabled organisations(pilot sites)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/EnabledOrganisationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OfferingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/EnabledOrganisationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/RecordTransformersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

https://trello.com/c/g5vBlFVc/1399-ability-to-allow-referrals-at-specific-sites
Restrict offerings and referrals to pilot sites ( data held in enabledOrganisation table) only

1399 ability to allow referrals

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

Rather than return a runtime exception - return a business exception which could in the future be handled by the front end - at the moment Runtime errors cause a 500 error in the front end. Where as the Business Exception will cause a 400 error with an explanation. 

returning business exception

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/update/CourseUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/db/migration/V53__add_audience_color_to_course.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseEntityFactory.kt

https://trello.com/c/sEF8y4PT/1418-api-changes-to-courses-offerings-endpoints
* Add a new field to store background colour of audience
* update existing courses withe the colour
* Add the `audience_colour` to the course response

1418 - audience background colour to be read from backend

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/main/resources/db/migration/V54__Add_hold_release_to_status.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

Add flags to the referral statuses to indicate that they are hold and release statuses.
This is to help the front end to determine whether or not to display the ‘put on hold’ or ‘release from hold’ buttons.
Need to add these flags to each endpoint that returns a status - so:
/referrals/{id}/status-transitions
/reference-data/referral-statuses
/reference-data/referral-statuses/{code}
[1465](https://trello.com/c/9yrFbAa8/1465-api-add-hold-and-release-flags-to-referral-status)

added hold and release flags to referral status

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusTransitionEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/resources/db/migration/V56__Add_description_hint_to_status_transitions.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

Currently there is a ‘hint text’ associated with the referral status. Sometimes during status transitions this text is different depending on what the status transition is.
Need to present the UI with this alternative hint text when it is present for the chosen transition.
[1464](https://trello.com/c/qIYcbWpo/1464-api-create-alternative-hint-text-for-status-transitions)

Added additional descriptions and hint text

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusTransitionEntity.kt
src/main/resources/db/migration/V57__Add_default_order_to_status.sql

An attempt at ordering statuses. Have gone with a weighting approach rather than specific ordering since statuses can appear on any lists. but as a rule of thumb withdrawn is at the bottom, then not suitable, on hold, not eligible then everything else. 

Initial attempt at status ordering

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

fixed to take notice of ptUser flag

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/resources/db/migration/V63__Status_transition_withdraw_confirm_text.sql

Added specific rules for deselection

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt

Removed warning text on programme complete transition

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/resources/db/migration/V67__Update_course_name_referral_view.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

Updating the way course name is displayed in list screens so that the course has the strand information in it. 
[1529](https://trello.com/c/wEmxE1EZ/1529-fix-programme-name-in-referrer-case-list)

added course display name for list screens

---

.circleci/config.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

Added endpoint to return performance statistics for various status transitions: 
Example URL:
https://accredited-programmes-api-dev.hmpps.service.justice.gov.uk/statistics/performance/status-duration?startDate=2022-01-01&statuses=REFERRAL_SUBMITTED,AWAITING_ASSESSMENT
{
"performance": [
{
"status": "AWAITING_ASSESSMENT",
"averageDuration": "41 hours 30 minutes 57 seconds",
"averageDurationUnderOneHour": "00 hours 01 minutes 21 seconds",
"minDuration": "00 hours 00 minutes 01 seconds",
"maxDuration": "1677 hours 29 minutes 30 seconds"
},
{
"status": "REFERRAL_SUBMITTED",
"averageDuration": "87 hours 47 minutes 08 seconds",
"averageDurationUnderOneHour": "00 hours 01 minutes 01 seconds",
"minDuration": "00 hours 00 minutes 01 seconds",
"maxDuration": "1846 hours 40 minutes 04 seconds"
}
]
} …

added endpoint to get performance figures for status transitions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

following discussions with UI team - decided to change the put offerings from a list to a single item. Also added a post offering to make it clearer what is being done. 

change to put/post endpoints for offerings

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/OfferingRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

The default hibernate.delete method doesn't work for offering (really not sure why as it works for course) 
Anyway I've added a delete query which does work, feels like a hack and will look into this again at some point. 
Also added additional tests. 

fix to offering delete

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/PniResultEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/LearningNeeds.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/NeedsScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/OasysTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/main/resources/db/migration/V93__add_basic_skills_score_to_pni_result.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt

(https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?selectedIssue=APG-390)
- Add new column for basic skills test to pni_results table
- Add basic skills score to NeedsScore to allow persistence as JSON
- Update corresponding entity class to reflect the above
- Updates to PniService implementation to retrieve basic skills score and persist
- Updates to integration test to verify score is saved

APG 390 store basic skills score

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralStatusHistory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatusHistoryIntegrationTest.kt

- Update integration test to verify reason code is returned for getReferralStatusHistories controller endpoint
- Remove spurious call to service from controller method

APG 330 return reason in status history

---

.circleci/config.yml
README.md
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/StatisticsController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/AuditIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatisticsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/OfferingRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/ReferralRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseParticipationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/OfferingControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/OrganisationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/PeopleControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/resources/application-test-h2.yml
src/test/resources/application-test.yml

Enable the return of report counts for referrals with a status of ON_PROGRAMME 
- Update StatisticsController to enable returning of ON PROGRAMME report types
- Update StatisticsIntegrationTest to verify correct behaviour when returning ON PROGRAMME reports types
- Enabled using Postgres as a backend for Integration tests with test containers and updated IntegrationTestBase accordingly
- Added additional test config yaml for H2 databases to allow existing tests that use it to continue doing so
- Updated the active Spring Boot profile for tests that use an H2 backend
- Enabled remote docker for circleCi to allow test containers to execute
ready …

APG 409 return on programme count

---

.gitignore
postman/collections/Accredited Programmes API.postman_collection.json
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralStatusType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

Allow for the retrieval of all referral reasons in one hit based on a type of either DESELECTED or WITHDRAWN
- Add new endpoint to API to retrieve all referral reasons for the provided type
- Added corresponding service implementation and repository code 
- Added Integration tests to validate the correct behaviour
- Minor update to application.yaml to allow for local service startup
- Update to postman collection for new endpoint

APG 387 return all referral status reasons

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseParticipationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/CourseParticipation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/CourseParticipationTransformers.kt
src/main/resources/db/migration/V95__add_referral_id_to_course_participation.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PeopleControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseParticipationRepositoryIntegrationTest.kt

Associate referrals with course participation and allow referall id to be returned with course participation data from API
1. 
2. Included a new `referral_id` column to the `course_participation` table with necessary foreign key constraints. 
3. Updated corresponding data models and tests to include and validate this new field.

APG-461 Add referral ID to course participation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/type/SaraRisk.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/type/SaraRiskTest.kt

1. Modified the `fromString` method in the `SaraRisk` class to return `NOT_APPLICABLE` instead of throwing an `IllegalArgumentException` when an unknown value is provided. 
2. Updated the unit tests to reflect this change and to ensure that this new behavior is properly validated.

Ensure appropriate behaviour for null Sara score 

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/IndividualNeedsScores.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/NeedsScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualCognitiveScoresTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualRelationshipScoresTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualSelfManagementScoresTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualSexScoresTest.kt

- Changed various domain score methods to return `null` instead of `0` when total scores are zero. 
- This ensures `null` values are accurately handled and used in calculations, providing a more precise representation of scores. 
- Updated relevant tests and methods accordingly.

Make PNI domain scores nullable to accurately represent missing values

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/IndividualNeedsScores.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualCognitiveScoresTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualRelationshipScoresTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualSelfManagementScoresTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualSexScoresTest.kt

Ensure overall scores for PNI constituent scores are null if any of the individual scores are null
NB. This appears to alter the overall PNI risk score.
Updated IndividualNeedsScores calculation logic to integrate a new extension function that checks for null values in data class properties. Adjusted parameterized tests accordingly to ensure robustness in scenarios with partial data, improving the validation of score computations.

Refactor score calculations to handle null values in test cases

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysApiIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysServiceTest.kt
src/test/resources/simulations/__files/assessments.json
src/test/resources/simulations/__files/relationships-with-SARA.json
src/test/resources/simulations/mappings/oasys.json

Ensure only risk score calculation will use the Oasys relationship data from a completed assessment with populated SARA info.
- Refactor PniService to handle completed SARA assessments more accurately by changing variable names and refactoring method calls
- Add and modify JSON test files to include new SARA fields and ensure that integration tests reflect the updated logic.

[APG-514] Refactor PniService to ensure only Risk scores use assessment with SARA

---

script/kubernetes-scripts/README.md
script/kubernetes-scripts/setup-service-pod.bash

- Introduce a new script `setup-service-pod.bash` to automate the creation and management of service pods. This script sets up IRSA-based authentication and allows users to perform authorized AWS commands. 
- Updated the README with usage instructions and examples for interacting with AWS RDS.

APG-535 Add setup-service-pod script for easy service pod management

---

build.gradle.kts

- Override netty-common version to address vulnerability GHSA-xq3w-v528-46rv by updating to version 4.1.115.Final. 
- Update wiremock-standalone dependency from 3.0.1 to 3.9.2.

APG-515 Update dependencies to address security vulnerability

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OfferingController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

Unknown offering ids were causing spurious 500 errors to be returned from the API. Return 404 instead.
- Streamline the `getOfferingById` endpoint method 
- Added an integration test to verify the 404 response for unknown offering IDs.

APG -568 Refactor `getOfferingById` endpoint to improve null handling

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OrganisationController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/DomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OrganisationControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PeopleControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatisticsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatusHistoryIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/OrganisationControllerTest.kt

- Refactored getAllCoursesByOrganisationId API endpoint to return withdrawn courses
- Added new integration test for the OrganisationController to verify retrieval of courses by organisation code. 
- Updated existing JUnit tests to reflect refactoring 
- Corrected several instances of a typo in method names from `createdOrganisation` to `createOrganisation` in various test files.

[APG-559] Ensure withdrawn courses are returned from OrganisationController

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseControllerTest.kt

- Replaced calls to `getNotWithdrawnCourseById` with `getCourseById` to include withdrawn courses in results.
- Updated and added integration tests to reflect the changes and ensure withdrawn courses are properly returned. 
- Added `withdrawn` property handling in `RecordTransformers`.

[APG-559] Refactor course endpoints to handle withdrawn courses

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngineTest.kt

The Oasys API can return both null and "Not Applicable" for OSP values, which we need to handle appropriately.
- Refactor `isRsrHigh` and `isRsrMedium` methods to handle "Not Applicable" OSP scores. 
- Added corresponding unit tests to ensure risk classification logic is accurately validated.

[APG-584] Handle Oasys Not Applicable OSP value

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysOffenceDetail.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/OffenceDetail.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysServiceTest.kt
src/test/resources/simulations/__files/offence-detail.json

- Update Oasys and Model dto data classes to correctly map field as String
- Update JUnit, integration test, and wiremock data file

[APG-589] Update Offence detail mapping for numberOfOthersInvolved field

---

src/main/resources/db/migration/V105__fix_hmp_wymott_offerings.sql

Currently HMP Wymott are able to see the “New Me Strengths” programme as a referable option which should not be the case.
Created a data fix SQL script to set the withdrawn flag to true for the course offerings available at Wymott Prison for the New Me Strengths programme with the course identifier of NMS-AO  

[APG-596] Fix HMP Wymott course offerings withdrawal status.

---

helm_deploy/hmpps-accredited-programmes-api/templates/cronjob-prod-to-preprod-data-refresh.yaml

Fixed typo for referrer_user table in data replication cronjob yaml 

[APG-361] Fix table name in data refresh cronjob.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

- Refactor the PNI persistence mechanism to save PNI data only when the referral status is updated to "On Programme". 
- Added JUnit and Integration tests to validate this behaviour and ensure PNI is not stored prematurely or inappropriately. 

[APG-523] Update PNI persistence logic in ReferralService

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/resources/simulations/mappings/allocation-manager-api.json

Add integration test that verifies that referral submission completes successfully in the scenario that the allocation manager API returns a 404 when querying POM details.

APG 604 add 404 integration test for referral submission

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseParticipationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseParticipationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PeopleControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseParticipationRepositoryIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

Once a referral has been submitted, any new programme history that was added as part of that referral should no longer be flagged as ‘draft programme history’. It is no longer draft and therefore cannot be changed or updated in the future.
- Added functionality to update draft statuses of course participations to false when their associated referral is submitted. 
- Added accompanying tests for validation and repository updates to support the feature.

APG 464 update draft status to false on referral submission

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseParticipationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseParticipationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PeopleControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralStatusRefDataFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseParticipationRepositoryIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt

- Introduced a method to delete all course participations related to a specific referral. 
- Updated the service, controller, and repository to support this behavior. 
- Added Junit and Integration tests to verify behaviour
- Refactored usage of helper factory methods to ensure consistency.

[APG-576] Delete course participations on draft referral delete

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/type/SentenceCategoryType.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/type/SentenceCategoryTypeTest.kt

- Fix to ensure that sentence category types of DETERMINATE_RECALL and INDETERMINATE_RECALL are correctly mapped.

[APG-634] Add handling for DETERMINATE_RECALL and INDETERMINATE_RECALL categories

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseParticipationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/projection/CourseParticipationProjection.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseParticipationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/CourseParticipation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/CourseParticipationOutcome.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/CourseParticipationSetting.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/CourseParticipationTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseParticipationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/type/SentenceCategoryTypeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt

- Introduced `CourseParticipationProjection` to support fetching course participation details, including referral status, via repository projection. 
- Updated related components, such as service, transformers, and controller, to utilise this projection. 
- Renamed and enhanced integration tests to validate the new behaviour.

[APG-592] Add projection for course participation with referral status

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/StatisticsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReportStatusCount.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StatisticsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatisticsControllerIntegrationTest.kt

Introduce a new endpoint to retrieve referral status counts for a specified programme and location. This includes changes to the repository, service, and controller to handle the query logic, as well as relevant integration tests for validation.

[APG-545] Add statistics endpoint for referral counts by programme

---

helm_deploy/hmpps-accredited-programmes-api/values.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

- Increase JVM max heap size from 512 MB to 2048 MB in  the `JAVA_OPTS` environment variable.

[APG-665] Increase Java memory allocation to 2048m in values.yaml

---

src/main/resources/seed/db/migration/R__Seed_Data.sql

- Delete `course_variant` table data during seed reset

[APG-665] Delete `course_variant` data during seed reset

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseParticipationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseParticipationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

- Replaced duplicate logic with a unified `createOrUpdateCourseParticipation` method. This ensures existing course participation records are updated when applicable, improving code maintainability and consistency.
- Added courseId mapping to CourseParticipationEntity
- Added additional integration tests to verify updated behaviour

[APG-672] Refactor handling of course participation creation

---

src/main/resources/db/migration/V118__update_referral_status_for_building_choices.sql

This migration updates the `referral_status` table to set `active` to `false` for the status `MOVED_TO_BUILDING_CHOICES`. It ensures the status is no longer flagged as active in the database.

[APG-732] Deactivate referral status for 'MOVED_TO_BUILDING_CHOICES.'

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V119__remove_building_choices_from_referral_status_transitions.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt

- Remove building choices from referral status transitions table in database 
- Update tests to verify the referral transition cannot occur
- Remove status transition check from transfer to building choices

[APG-732] Remove building choices from referral status transitions

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OrganisationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/PersonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/CourseVariantEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatisticsControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseParticipationRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/OfferingRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/ReferralRepositoryTest.kt

- Upgraded Hibernate to version 6.6.9.Final which broke 100+ Integration tests as a result of stricter checks when persisting detached entities.
- This was fixed by:
1.  Ensuring all Entities have a default value of null for their @Id fields
2. Updating relevant tests and entities to reflect these changes.

[APG-730] Bump up hibernate version and associated refactor

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysLearning.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/PniCalculation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/IndividualRiskScores.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/NeedsScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/Sara.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniServiceIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/simulations/__files/oasys-pni-response-success.json
src/test/resources/simulations/mappings/oasys.json

- Introduce mapping logic in PNI related model data classes to correctly map from Oasys returned PniResponse model
- Refactor PniService creating separate methods for PNI score retrieval and persisting of PNI due to separation of concerns
- Added deprecation annotations to existing PniService methods
- Added integration tests to verify PNI score retrieval and persistence

[APG-737] Refactor PNI service methods to utilise Oasys returned PNI Score

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/PniAssessment.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/OasysApiClientIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysServiceTest.kt
src/test/resources/simulations/__files/oasys-pni-response-success.json

- Fix prod defect where incorrect enum was used to map Risk score level
- Renamed Oasys model enum to guarantee proper mapping

[APG-786] Refactor to replace ScoreLevel with RiskScoreLevel

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/StatisticsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/StatusCountByProgramme.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StatisticsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatisticsControllerIntegrationTest.kt

- Replaced `courseId` with `courseName` across the referral statistics API and related logic. 
- Added `StatusCountByProgramme` model to support this change. 
- Updated tests, services, and repository queries to reflect the updated logic.

[APG-768] Refactor referral statistics to use course name instead of ID

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OfferingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

We are seeing some optimistic locking exceptions in the API logs which may have resulted from refactoring JPA entities to non data classes.
- Isolated service tier code that performs updates on entities to ensure both fetching of entities and updating of persistent entites occurs within a single transactional boundary
- Added missing integration test for updating a course offering
- Belt and braces : added equals and hashcode methods to course, offering and referral entities
- Corresponding Junit & Integration test updates

[APG-807] Refactor course handling logic and optimize test data setup.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/AudienceEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OfferingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OrganisationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OrganisationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/CourseRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/OfferingRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/ReferralRepositoryTest.kt

- Removed `@GeneratedValue` annotation from JPA Entities where Id field is set manually
- Updated corresponding service code
- Updated affected Integration tests

[APG-807] Remove spurious @GeneratedValue annotation from JPA Entities

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt

- Move referral retrieval logic from controller to referral service
- Prevent referral ldc flag persistent update during GET operation

[APG-808] Encapsulate referral fetching logic in ReferralService

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OfferingEntity.kt

- Remove `@Version` annotation from Course and Offering entities

[APG-808] Remove Version annotation from course and offering entities

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

- Updated logic to return 404 responses when no matching BC courses are found. 
- Additional test to ensure correct behaviour for new scenarios.
- Renamed `getBuildingChoicesCourses` to `getAllBuildingChoicesCourses` for clarity and consistency. 

[APG-818] Small refactor for returning Building Choices courses

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/update/ReferralUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/Referral.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V127__add_has_reviewed_info_flag_to_referral.sql
src/main/resources/db/migration/V128__add_has_reviewed_info_flag_to_referral.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt

- Added new flag to store whether a user has reviewed the additional information for a referral on the referral JPA entity
- Created corresponding column on referral table via flyway script
- Added SQL to update existing draft referrals with appropriate flag value
- Added an integration test to verify new scenario where additional information can be null

APG-780 add has reviewed additional info flag to referral

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/PniAssessment.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniServiceIntegrationTest.kt
src/test/resources/simulations/__files/oasys-pni-response-no-osp-success.json
src/test/resources/simulations/mappings/oasys.json

- Updated model objects for Oasys PniResponse to allow for null OSP values
- Added integration test to verify 

[APG-804] Handle null OSP value from Oasys

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralStatusType.kt
src/main/resources/db/migration/V129__add_assessed_as_suitable_categories.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

- Introduced a new referral status type 'ASSESSED_SUITABLE' with associated categories and reasons in the database. 
- Updated API endpoints, documentation, and tests to support fetching and validating this new status type and its reasons.

APG-791 Add new referral status categories for ASSESSED_SUITABLE status type

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralStatusReason.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

- Introduce `categoryDescription` field to referral status reasons, aligning database queries, projections, and transformations accordingly. 
- Updated tests to validate the new field and ensure correct integration into the referral response. 

[APG-829] Add category description to referral status reasons

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PNIControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniServiceIntegrationTest.kt
src/test/resources/simulations/__files/oasys-pni-response-no-osp-success.json
src/test/resources/simulations/mappings/oasys.json

- Updates to return LDC score as part of Learning and Needs basic skills score as part of PNI details
- Refactor LDC score to use integers instead of BigDecimal to reduce unnecessary conversion (API returns an Int)
- Updated LDC score processing to use integer types for consistency and simplified threshold comparison logic. 
- Adjusted and added integration tests and mock data to align with the changes

[APG-838] Return LDC score with PNI details

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

- Commented ModSecurity-related lines have been removed from the production, development, and pre-production Helm values files. 

[APG-844] Remove commented-out ModSecurity settings from Helm values.

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt

- Upgraded PostgreSQL container from version 15.1 to 16.4 for our integration tests, to align with desired version in production environment

[APG-536] Update PostgreSQL version in IntegrationTestBase

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt

**WHAT**
This is a pure-refactor commit, i.e. it introduces no new functionality.
Made the following changes to the getNextStatusTransitions endpoint (i.e. `GET /referrals/{id}/status-transitions`):
- Added the `@Operation` annotation
- Replaced the `@GetMapping` annotation with the `@RequestMapping`
- Return a 404 if the Referral isn't found (don't coerce non-null)
- Refactored the logic to stop re-finding of the same status (i.e. the DESELECTED code)
**WHY**
As part of getting more familiar with Kotlin and the AcP codebase(s), I have been getting familiar with the patterns used.
While looking around, it appeared that this endpoint was broadly inconsistent with the others.

Refactor: Add documentation to the getNextStatusTransitions endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/StatisticsController.kt

Marks stats/reporting endpoints that are not in use by the UI as deprecated

Marks stats/reporting endpoints that are not in use by the UI as deprecated

---

helm_deploy/hmpps-accredited-programmes-api/templates/cronjob-prod-to-preprod-data-refresh.yaml

- Upgraded the PostgreSQL image in the cronjob from version 14 to 16. 

[APG-536] Update PostgreSQL version in prod-to-preprod data refresh

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/simulations/__files/prison-search-results_A9999BB.json
src/test/resources/simulations/mappings/prison-api.json

- Refactored the PNI storage method to retrieve the PNI score from OASys before saving for referral status updates to ON_PROGRAMME
- Updated affected tests and wiremock data to reflect the new workflow, including additional verifications and corrections to prison numbers.

[APG-778] Refactor PNI storage logic to retrieve score from Oasys

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

When status code is set to DESELECTED, the deselectAndKeepOpen param will filter the reasons further by whether the referral is be closed or kept open

APG-837 - Adds deselectAndKeepOpen filter to findReferralStatusReasonsByStatusCode

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

[APG-852] Updating API response for swagger
[APG-852]: https://dsdmoj.atlassian.net/browse/APG-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APG-852] Update response spec for delete test referrals API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/PrisonSearchController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralStatusRefData.kt

- **chore(PrisonSearchController): Add the 'deprecated' field to the deprecated endpoints.**
- **chore(ReferralStatusRefData): Improve documentation annotations; remove redundant/duplicated Javadoc documentation**

Gardening: Clean up documentation for ReferralReferenceData; Update deprecated annotation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OrganisationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/type/Gender.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OrganisationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/CourseOffering.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OrganisationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/OrganisationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/RecordTransformersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

- Moved the Gender enum to a dedicated package and replaces the String-based gender representation across the codebase. It ensures consistency, improves type safety, and reduces duplication by centralising gender logic in the shared `Gender` enum.
- Added the "ANY" gender type in lieu of incoming nationwide location refactoring

[APG-923] Refactor gender handling to use centralised Gender enum.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/type/SentenceCategoryType.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/type/SentenceCategoryTypeTest.kt

- Updated logic to handle combinations of DETERMINATE and RECALL, as well as INDETERMINATE and RECALL. 
- Enhanced corresponding unit tests to validate new scenarios and ensure consistent behaviour.

[APG-924] Add support for new sentence category combinations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/ScoredAnswer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PNIControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniServiceIntegrationTest.kt
src/test/resources/simulations/__files/oasys-pni-response-success.json

-  `getPniInfoByPrisonNumber` API endpoint returns null values when values are missing rather than zero which represents no issues present for a particular risk or need.

[APG-944] Handle nullable scores in PNI models and tests

---

helm_deploy/hmpps-accredited-programmes-api/templates/cronjob-data-extractor-analytics.yaml

We had a critical alert from dependabot in the data extractor repository which required us to bump a few dependencies and create a new release. This PR bumps the data extractor to the latest release. We've tested this with the calculate-release-dates service and it worked without issue. Hope this is ok - happy to discuss. Thanks!
Data extractor version bump

Update data extractor to latest
