ministryofjustice/hmpps-accredited-programmes-api

.circleci/config.yml
Dockerfile
build.gradle.kts

Update project dependencies following guidance generated by renovate bot.

:arrow_up: :pushpin: Respond to renovate[bot] update hints by updating dependencies and pinning where advised.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/inmemoryrepo/InMemoryCourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/transformer/Transformers.kt
src/main/resources/db/migration/V5__drop_type_column_from_course_table.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/CourseAudienceRelationshipTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/jparepo/CourseEntityRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/transformer/TransformerTest.kt
src/test/resources/db/migration/R__test_data.sql

Trello: [467](https://trello.com/c/lJ8CfbpL/467-remove-type-from-courseentity)
Does what it says on the tin.

467 Remove `type` from `CourseEntity`

---

build.gradle.kts

Bump the version of the Gradle plugin 'uk.gov.justice.hmpps.gradle-spring-boot' in response to renovate bot.

:arrow_up: Update the 'uk.gov.justice.hmpps.gradle-spring-boot' gradle plugin version.

---

src/main/resources/application.yml

417 :bug: Remove space from the end of the database name in application.yml!!!!

---

build.gradle.kts
helm_deploy/hmpps-accredited-programmes-api/Chart.yaml

* Minor update to  gradle build file plug-in dependencies.
* Updated Helm chart dependencies
Both changes in response to renovate bot. New version numbers suggested by renovate bot.

Gradle build and helm chart dependency updates; responding to advice from renovate bot.

---

doc/how-to/manage-infrastructure.md
doc/how-to/view-application-logs.md

https://trello.com/c/aMMpgJkt/332-add-documentation-for-debugging-infrastructure-in-the-service-ui-and-api
Adds docs for managing infrastructure with reference to tools like Kubernetes, Kibana and the MOJ Cloud Platform Environments project.
This includes instructions for viewing logs, debugging deployments, restarting services etc.
It's very much copied and pasted/adapted from the Community Accommodation team's guidance
[here](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4325244964/Manage+infrastructure)

(332) Add infrastructure documentation

---

src/main/resources/seed/db/migration/R__Seed_Data.sql

BWN wasn't and ID of a prison found in the Prison Register locally, so was always rendering empty offerings
This PR replaces references to BWN in the local seed data with the IDs of prisons that were found in the local environment.

Update seeded prisons

---

.github/workflows/codeql.yml

https://trello.com/c/HFbiMKKr/550-add-codeql-for-vulnerability-scanning
CodeQL will scan our code for any vulnerabilities with GitHub Actions.
Unfortunately there's not yet automated configuration for Kotlin as there is for TypeScript (which we've used on the UI repo), so we have to add our own config file.
Adds CodeQL config file to be run against `main` branch. This was mostly generated automatically when adding CodeQL in GitHub but I've made a few tweaks to have it line up with the same config used in the Approved Premises team [here](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/.github/workflows/codeql.yml)

(550) Create codeql.yml config

---

.github/PULL_REQUEST_TEMPLATE.md

This was splitting across multiple lines and looked a bit strange
Tidies up formatting in PR template post-merge checklist
release to preprod
release to prod

Fix formatting on PR template

---

src/main/resources/seed/db/migration/R__Seed_Data.sql

Request from Ynda.
Revised the audience values in R__Seed_Data.sql to align with those in the OBP directory.
This PR only changes test data.  Production artifacts are unaffected.

Our seed data is out of sync with the latest audience values in the OBP directory

---

doc/how-to/view-application-logs.md

https://trello.com/c/lIVDuXnb/611-add-infrastructure-documentation
Adds instructions for how to use Application Insights to view logs.

(611) Add docs for viewing logs in AppInsights

---

doc/adr/0004-bulk-replace-api-data.md
doc/how-to/replace-all-api-data.md

Trello [Document our approach to uploading data to the API](https://trello.com/c/crsvsg0L/556-document-our-approach-to-uploading-data-to-the-api)
* Added a how-to `replace-all-api-data.md`
* Added an ADR `0004-bulk-replace-api-data.md`
This PR does not affect the project's deployable artifacts.

556 Document our approach to uploading data to the API

---

build.gradle.kts

Updates in response to feedback from Renovate Bot.
Bump version numbers in build file `build.gradle.kts`

Update vulnerable dependencies to keep the application secure. 

---

src/main/resources/seed/db/migration/R__Seed_Data.sql

We use the seeds in local UI development. We can't add courses in the UI, so it's useful to have courses that represent all the different cases we need to cover
- Add a seeded non-referable course for use in UI development

(677b) Add non-referable course seed

---

script/kubernetes-scripts/download-csvs
script/kubernetes-scripts/get-token
script/kubernetes-scripts/upload-csvs

Trello:  [Add scripts for updating course data](https://trello.com/c/sooyolH2/614-add-scripts-for-updating-course-offering-data-in-the-service)
* Fixed scripts for downloading and uploading CSV format representations of courses from the Kubernetes `dev`, `preprod` and `prod` environments.
* Updated the `get-token` script to align with changes to the prod and preprod auth secrets.
Tested against dev and preprod environments.
These support scripts are not deployed to production environments.

416 Update scripts for bulk download and upload of course data in CSV format.

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/resources/db/migration/R__test_data.sql

https://trello.com/c/gB76GqkW
Pact tests had been disabled in the past. As part of this ticket we have updated the pact provider tests to satisfy the consumer. 

788 add missing pact contract tests referrals and course participations 

---

doc/adr/0005-use-api-for-aggregating-data-for-caselists.md
doc/adr/0006-avoid-caching-caselist-endpoint-data-until-we-re-sure-we-need-it.md

https://trello.com/c/eKCVfadw/1047-spike-how-do-we-handle-fetching-and-caching-data-from-other-services-for-the-caselist-endpoint-m
Adds a couple of ADRs to document our approaches to building the API, including how we'll handle caching if we decide to go down that route.

(1047) Document our approach to building the caselist API and caching

---

README.md

Deployments are currently failing for some reason. Adding a newline to see if we can get it to pass again on `main` without reverting #167 

Add newline to test deployments

---

src/test/resources/db/migration/R__test_data.sql

Recent builds have caused significant issues with the dev environment.
We identified the problem branch in PR #162, which has since been reverted in #167.
This PR reintroduces some of the changes to the repeatable flyway test migration, which should not break the dev branch.

Re-add changes to repeatable flyway migration (R__)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/read/ReferralSummaryProjection.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralSummaryProjectionFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/repository/ReferralRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/ReferralTransformersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

Recent builds have caused significant issues with the dev environment.
We identified the problem branch in PR #162, which has since been reverted in #167.
This is the second of two PRs which attempt to fix the issue; the first being flyway-related in #170.

Re-add & edit fields for data returned from caselist endpoint

---

docker-compose.yml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/model/SentenceAndOffenceDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonSearchApi/PrisonerSearchApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonSearchApi/model/Prisoner.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonSearchApi/model/PrisonerNumbers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/WebClientConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/response/model/SentenceAndOffenceDetails.kt
src/main/resources/application-local.yml
src/main/resources/application.yml
src/test/resources/application-test.yml

https://trello.com/c/LKPG1BwN/805-integrate-with-the-prisoner-search-api-m
As part of this PR we are adding a prison-search-api client with 1 methods to getPrisoners details by prisonId 
Setting up of the prison-search-api locally has been tricky and local testing is challenged by the lack of data. We have tested the endpoint by point at the dev env and we are able to get a response

805 create prisoner search api client

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/resources/db/migration/R__test_data.sql

- specify submitted on? why/where does this matter?
Keeping the API and UI in line with Pact tests is becoming a burden, and we appear to be creating a bunch of test data that we don't need
Related UI PRs:
- https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/pull/377
- https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/pull/379
This updates the Pact states match the latest UI tests and removes data that aren't being used anywhere

(1167c) Update/tidy Pact tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/resources/static/api.yml

make the referrerId field as optional when creating referral

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

make the referrerId field non mandatory

---

.gitignore
build.gradle.kts
docker-compose.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/AuthorisableActionResult.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonSearchApi/PrisonerSearchApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralSummaryBuilderService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/TestPropertiesInitializer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonSearchApi/PrisonerSearchApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/JwtAuthHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralSummaryBuilderServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/transformer/ReferralTransformersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/application-test.yml

[](https://trello.com/c/t8Xd0A3H/1096-add-fields-from-external-apis-to-caselists-endpoint-m)
* ReferralSummary to return values fetched from prison search and prisoner search api
* We use wiremock to mock the response in our tests

1096 fetch data from prison register api and prisoner search api

---

src/main/resources/application.yml

Increase log level to debug dev deployment

Increase log level to debug dev deployment

---

src/main/resources/db/migration/V26__retire_referrerId.sql

fix flyway referrer_user_username_fk

---

src/main/resources/application.yml
src/main/resources/logback-spring.xml

Rollback changes as debugging is complete

---

.trivyignore
build.gradle.kts

update spring boot and spring plugin versions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/projection/ReferralSummaryProjection.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralSummaryBuilderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/SecurityService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralSummaryProjectionFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralSummaryBuilderServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/SecurityServiceTest.kt

[](https://trello.com/c/4OFOa2kE/1046-build-api-endpoint-for-returning-the-current-users-referrals-m)
* Create a new endpoint to return current users referral - getReferralSummariesByUsername 
* Endpoint- "/referrals/me/dashboard" 
* Get the current logged in user from SecurityContext
* Get the data from db, fetch prison register and prisoner search details
* Map all the data to form the ReferralSummary

Fetch current users referral

---

build.gradle.kts

This should fix some vulnerabilities in our dependencies.

Update HMPPS gradle spring boot

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysAssessmentTimeline.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysApiServiceTest.kt
src/test/resources/simulations/__files/assessments.json

Updated the model coming back from Probation integration Oasys api to match what they are sending
[ticket 1212](https://trello.com/c/wh5s20Us/1212-set-up-integration-with-oasys-api-l)

updated api model to match probation integration model

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/OasysApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysLifestyle.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OasysController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/OasysTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysApiIntegrationTest.kt
src/test/resources/simulations/__files/lifestyle.json
src/test/resources/simulations/mappings/oasys.json

New endpoint to return lifestyle information from Oasys:
```
/oasys/[prisonNumber]/lifestyle
{
"activitiesEncourageOffending":"0-No problems"
"lifestyleIssues":"free text"
}
```
[1215](https://trello.com/c/vm0fte8V/1215-add-oasys-section-7-page-endpoint-lifestyle-and-associates-s)

OASys section 7 page endpoint (Lifestyle)

---

postman/collections/Accredited Programmes API.postman_collection.json
postman/collections/Prison Register API.postman_collection.json
postman/collections/Prisoner Search.postman_collection.json
postman/environments/Local.postman_environment.json

Our Postman team is full, and it's useful to have the collections living in the repo to help devs test things out locally.
Adds Postman collections and local environment variables (with nothing sensitive!) to the repo.

Add postman collections

---

doc/how-to/access-dev-database-remotely.md

Document the process for connecting to dev database.
[1305](https://trello.com/c/VL30kpoL/1305-set-up-and-document-remote-database-access)

Added instructions to enable local dev db accesss

---

src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysApiIntegrationTest.kt

small bug with the mapping of rosh summary source

---

src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysApiIntegrationTest.kt

Update endpoint name to match UI

updated endpoint name

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysLearning.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/OasysTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysApiIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysApiServiceTest.kt
src/test/resources/simulations/__files/assessments.json

I've noticed that the latest assessment brought back from Oasys is not a Layer 3 assessment so have put in an additional filter for this. 
Also the learning needs score description was discussed earlier in the week and have added the description as per that conversation. 

Small Oasys updates

---

src/main/resources/static/api.yml

Previously set this parameter to true in order to do some testing in dev. Now setting back to false. 
[1302](https://trello.com/c/IpxbwG3o/1302-fetch-and-update-person-in-prisons-details-when-viewing-a-referral-s)

updated default value for update person flag

---

src/main/resources/db/migration/V32__add_prison_table.sql

https://trello.com/c/WvDsOYFf/1301-fetch-and-store-prison-name-when-creating-a-referral-m
* Table structure for organisation

[1301] - Create organisation table

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

pagination/sorting wasn't quite working correctly. This PR should fix that

Fixed sorting issue

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/resources/db/migration/V35__update_referral_view.sql
src/main/resources/static/api.yml

Added release date type

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

added update method for organisations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/PrisonerSearchApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

General tidy up of unused code and tests etc. 

General code tidy

---

build.gradle.kts

updated SB version

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/resources/db/migration/V36__add_referral_status_table.sql
src/main/resources/db/migration/V37__referral_status_seed.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

Implementation of referral status reference data API and seed data from design documentation
Hierarchy is: 
Referral status -> referral category -> referral status reason
categories and reasons are optional.
[1345](https://trello.com/c/AWOQ0DHe/1345-reference-data-api)

Referral status reference data

---

src/main/resources/db/migration/V39__Referral_status_assessment_started.sql

added missing status of assessment started

---

build.gradle.kts

rolling back spring security version

---

build.gradle.kts

update spring security version

---

src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatusHistoryIntegrationTest.kt

removed trailing / from statushistory URl

---

doc/how-to/generate-workflow-diagram.md
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

added status flow diagram instructions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

fix for status group on case list endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/resources/db/migration/V37__referral_status_seed.sql
src/main/resources/db/migration/V49__Add_has_notes_to_status.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

Extra flags for has notes and has confirmation so that the front end can be as generic as possible. And descriptions of the statuses and confirmation text for the same reason. 

added extra status flags and data

---

helm_deploy/hmpps-accredited-programmes-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

https://trello.com/c/HJVytjBL/1359-create-be-client-to-write-to-sqs-queue
* Change audit config for each environment

adding env specific config

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

updated yaml alignment

---

helm_deploy/hmpps-accredited-programmes-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

reverted audit yaml helm changes

---

helm_deploy/hmpps-accredited-programmes-api/Chart.yaml

reverted helm changes

---

build.gradle.kts
helm_deploy/hmpps-accredited-programmes-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/PrisonSearchController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ExternalAuditService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

https://trello.com/c/HywWuVWU/1374-write-audit-messages
* Write audit messages to sqs

1374 - write audit events

---

helm_deploy/values-dev.yaml

adding WAF and OWASP rules

---

helm_deploy/values-dev.yaml

https://trello.com/c/HywWuVWU/1374-write-audit-messages
* We are changing the log level in dev env to see the audit messages come through

1374 - adding debug log level in dev

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/db/migration/V51__Add_legacy_courses.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseControllerTest.kt

Added ability to return all courses including legacy ones

---

helm_deploy/values-dev.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ExternalAuditService.kt
src/main/resources/logback-spring.xml

1374 - adding logging to test audit

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/model/SentenceAndOffenceDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/model/SentenceInformation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/PersonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseParticipationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V52__Add_sentence_type.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PersonSentencesIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PersonEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/simulations/__files/sentence-info.json
src/test/resources/simulations/mappings/prison-api.json

added sentence type to referral view

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Added OWASP and WAF rules for preprod and prod

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/model/SentenceInformation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt
src/test/resources/simulations/__files/sentence-info.json

minor changes following manual testing

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/InternalAuditService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

* Write correct audit Type message on update

1374 - write update audit records in internal audit table

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseEntityFactory.kt

1418 - Rename audience_colour to audienceColour in entity

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/main/resources/db/migration/V55__update_status_descriptions.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

Additional work to satisfty the bespoke deselection status journey

---

src/main/resources/db/migration/V58__update_default_order_to_status.sql

Update status ordering

---

src/main/resources/db/migration/V59__Updated_referral_submitted_hold.sql

update to remove hold text for referral submitted

---

src/main/resources/db/migration/V60__Status_transition_text_fixes.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

referral status updates

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusTransitionEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/resources/db/migration/V61__Add_confirmation_fields.sql
src/main/resources/static/api.yml

[1466](1466-api-custom-label-text-for-status-transitions)

api custom label text for status transitions

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

removed extra / from oasys path

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

added has confirmation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/BaseHMPPSClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/arnsApi/ArnsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/OasysApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/PrisonerSearchApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/exception/ServiceUnavailableException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/config/ApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/PrisonSearchController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PrisonRegisterApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PrisonerSearchApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/PrisonerSearchApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/config/ApiExceptionHandlerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

1440 - add exception when prison api is unavailable in base class

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/resources/db/migration/V62__status_transition_confirmation_text.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralReferenceDataIntegrationTest.kt

added bespoke confirmation text

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/BaseHMPPSClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PrisonRegisterApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PrisonerSearchApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

1440 - add exception when prison api is unavailable - adding logging

---

src/main/resources/db/migration/V64__fixes_for_on_programme.sql

additional status transition text

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

make WAF rule active

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/resources/db/migration/V65__fix_typos.sql

additional changes to support figma designs

---

Dockerfile

addressing ITHC concern

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

1496 - Add alerting for elasticcache and postgress db

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/AuditService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/resources/db/migration/V66__update_audit_table_auditAction.sql

 Fix old auditAction entires

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysAttitude.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysBehaviour.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysLifestyle.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysPsychiatric.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysRelationships.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/OasysTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysApiServiceTest.kt

https://trello.com/c/oxqMX03r/1501-add-pni-data-items-to-endpoint?filter=label:Tech

1501 add pni data to existing endpoints

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/AuditService.kt

1483 - save current status of referral

---

.circleci/config.yml

added SQS check

---

.circleci/config.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/listener/DomainEventsListener.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/DomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt

minor refactor

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

Removed manual update of prisoner

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/DomainEventsListenerTest.kt

remove failing test

---

.circleci/config.yml
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

change memory arguments

---

build.gradle.kts
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/ResourceLoader.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/DomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt
src/test/resources/simulations/mappings/prison-api.json
src/test/resources/simulations/mappings/prison-search-api.json

Updated test to test the complete update offender journey

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/AuditEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/AuditService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

Minor logging changes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/resources/static/api.yml

Added displayName to course

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt

removed alternative desc from displayName

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/pact/PactContractTest.kt

1454 Order prerequisite by description

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OrganisationController.kt

only return active courses

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/AuditService.kt

Debug token - dev only

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt

removing additional *the* from the message

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/OasysTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysApiIntegrationTest.kt

updating risks endpoint to return more useful risks data.
[APG-6](https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?label=Tech&selectedIssue=APG-6)
[APG-6]: https://dsdmoj.atlassian.net/browse/APG-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added additional alert data

---

src/main/resources/db/migration/V69__Update_warning_text_suitable_not_ready.sql

[](https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?selectedIssue=APG-66)

APG-66 Update warning text in SUITABLE_NOT_READY

---

src/main/resources/db/migration/V70__Update_status_transition_text.sql

[APG-70](https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?label=Tech&selectedIssue=APG-70)
[APG-70]: https://dsdmoj.atlassian.net/browse/APG-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update transition descriptions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseParticipationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/SubjectAccessRequestService.kt

attempt to fix a sql parameter error

---

src/main/resources/static/api.yml

APG-113 Update swagger tags

---

src/main/resources/db/migration/V71__Update_radio_button_hint_text.sql

https://dsdmoj.atlassian.net/browse/APG-76

APG-76 Update radio button hint text

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/SarsDataController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseParticipationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

adding pre authorise to class

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/OasysTransformer.kt
src/test/resources/simulations/__files/alerts.json

remove duplicate alerts

---

src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysApiIntegrationTest.kt

APG-113 minor swagger change

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralStatusHistoryService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatusHistoryIntegrationTest.kt

https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?label=API%2CTech&selectedIssue=APG-58

APG-58 Remove referral started from status history

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/config/SecurityConfiguration.kt

added swagger-ui to permit all

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/model/SentenceInformation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt
src/main/resources/application.yml
src/main/resources/static/api.yml

Update this endpoint to return the following key dates:
APD Approved parole date
ARD Automatic release date
CRD Conditional release date
ERSED Early removal scheme eligibility date
ETD Earliest transfer date
HDCAD Home detention curfew approved date
HDCED Home detention curfew eligibility date
MTD Mid term date
NPD Non-parole date
PED Parole eligibility date
PRRD Post recall release date
TERSED Tariff expired release scheme eligibility date
TED Tariff Expiry Date 
"keyDates": [
    {
      "type": "releaseDate",
      "description":"Conditional release date",
      "date": "2024-05-23",
      "earliestReleaseDate":true,
     "order": 1
    }
  ]
[APG-112](https://dsdmoj.atlassian.net/browse/APG-112)
[APG-86](https://dsdmoj.atlassian.net/browse/APG-86)
[Release process …

update key dates APG-112 and APG-86

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt

added sorting to key dates

---

src/main/resources/db/migration/V73__Withdraw_course_from_sites.sql

https://dsdmoj.atlassian.net/browse/APG-126

APG-126 Update find dir - remove courses from certain locations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

[APG-118](https://dsdmoj.atlassian.net/browse/APG-118)
[APG-118]: https://dsdmoj.atlassian.net/browse/APG-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update earliest release date calculation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonApi/model/SentenceInformation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PersonIntegrationTest.kt
src/test/resources/simulations/__files/sentence-info.json

fixed broken logic in earlisest release date logic

---

src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/TestPropertiesInitializer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

fixing a few code smells

---

.circleci/config.yml
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

revert dependency updates

---

.trivyignore
build.gradle.kts

rolling back this change

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

APG-146 do not display deleted referrals

---

.circleci/config.yml

APG-137 update orbs to 9.1.0

---

build.gradle.kts

Renovate uk.gov.justice.hmpps.gradle spring boot 6.x

---

.trivyignore
helm_deploy/hmpps-accredited-programmes-api/templates/cronjob-data-extractor-analytics.yaml
helm_deploy/hmpps-accredited-programmes-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Adding analytical platform config

---

src/main/resources/db/migration/V74__Update_status_transitions_secondary_desc.sql

https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?selectedIssue=APG-60

APG-60 update transition status secondary description

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

disabling analytical platform config

---

.circleci/config.yml
helm_deploy/hmpps-accredited-programmes-api/Chart.yaml
helm_deploy/hmpps-accredited-programmes-api/templates/cronjob-data-extractor-analytics.yaml

attempt to fix container issue

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

add analytical platform for prod

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt

added SED and LED key dates

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralReferenceDataService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V75__update_referral_status_order.sql
src/main/resources/static/api.yml

added default order on reference data

---

src/main/resources/db/migration/V76__change_heading_case.sql

fixed case

---

.circleci/config.yml

Update playwright docker image to 1.44.1 for circleci

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/main/resources/db/migration/V77__Add_notes_status_update.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

Update all status changes to add notes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/resources/db/migration/V78__Has_confirmation_status_update.sql
src/main/resources/static/api.yml

change to confirmation text rules

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/PrisonRegisterApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/model/Prison.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/model/PrisonLite.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OrganisationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PrisonRegisterApiService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PrisonRegisterIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/OrganisationControllerTest.kt
src/test/resources/simulations/__files/prison-register-all-prisons-results.json
src/test/resources/simulations/mappings/prison-register-api.json

APG-177 create new endpoint to return prisonId and prisonName

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt

change Release date to Confirmed release date

---

.circleci/config.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt

fix to sql

---

Dockerfile

https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?label=Tech&selectedIssue=APG-238

APG-238 update rds certs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/AudienceEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/AudienceRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/AudienceService.kt
src/main/resources/db/migration/V79__create_and_populate_audience.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

APG-178 add new api for audience

---

src/main/resources/db/migration/V79__create_and_populate_audience.sql
src/main/resources/static/api.yml

APG-178 update audience tag

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt

small changes to update course

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

API method to update/replace all prerequisites for a given course. 
[APG-182](https://dsdmoj.atlassian.net/browse/APG-182)
[APG-182]: https://dsdmoj.atlassian.net/browse/APG-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update course prerequisites

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/AudienceService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

APG-181 Create course API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/OfferingRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/OrganisationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/DomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

[APG-183](https://dsdmoj.atlassian.net/browse/APG-183)
[APG-184](https://dsdmoj.atlassian.net/browse/APG-184)
[APG-185](https://dsdmoj.atlassian.net/browse/APG-185)
[APG-183]: https://dsdmoj.atlassian.net/browse/APG-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APG-184]: https://dsdmoj.atlassian.net/browse/APG-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APG-185]: https://dsdmoj.atlassian.net/browse/APG-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

APG-184, APG-183, APG-185

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/model/Prisoner.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/PersonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V80__add_prisoner_location.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PersonEntityFactory.kt

APG-260 Add prisoner location to caselist view

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

Additional logs for refreshing offenders

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V81__update_prisoner_location.sql

APG-265 Update prison location to outside

---

src/main/resources/db/migration/V82__update_referral_view.sql

APG-267 do not return deleted referrals in caselist

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

Change to the order of status group/ status priority

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

removed logging

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatisticsIntegrationTest.kt

added multi location search and test

---

.circleci/config.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

fix to location codes

---

src/main/resources/static/_schemas.yml
src/main/resources/static/_shared.yml
src/main/resources/static/api.yml

Apg 266 split api yaml v2

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

Managed figure a way to do all of these tickets in one :-)
APG-208 APG-215, APG-212, APG-2214

endpoint to return counts

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

change to end date calculation since dates are timestamps in DB

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

[APG-209](https://dsdmoj.atlassian.net/browse/APG-209)
[APG-209]: https://dsdmoj.atlassian.net/browse/APG-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added status counts endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

include audience id

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

made course identifier optional

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

added endpoint to delete a course

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

added null protection

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

fix to sql and return results in days mins second

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt

change to SQL to parse days/minute/seconds for status durations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysRelationships.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/config/SwaggerConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysApiServiceTest.kt

APG-236 minor refactor - change curRelCloseFamily for PNI info

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

added link to documentation

---

src/main/resources/db/migration/V83__add_new_pilot_sites.sql

APG-290 - enable pilot site : Fosse Way

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/statistics/StatisticsController.kt

added link to documention

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt

changed prerequisite object

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonerSearchApi/model/Prisoner.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/PersonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V84__add_person_gender.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/util/TestConstants.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PersonEntityFactory.kt

add gender to person

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V85__add_missing_fk.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatusHistoryIntegrationTest.kt

added missing fk constraints

---

src/main/resources/db/migration/V86__add_peterborough_enabled_org.sql

APG-291 Add Peterborough to enabled organisations - new pilot site

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/NeedsScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt

APG-228 Classification score

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/controllers/ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/controllers/ReferralsController.kt

moved reference data out of open api

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualNeedsAndRiskScores.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/IndividualRiskScores.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/NeedsScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/PniScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/RiskScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngineTest.kt

APG-228 Risk score calculation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/prisonRegisterApi/model/Prison.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/PrisonTransformer.kt

APG-306 Make addressLine1 optional

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/PniRuleEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/PniRuleRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/pni/model/PniScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/main/resources/db/migration/V88__add_pni_rules.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngineTest.kt

APG-273 Exceptions logic for PNI

---

src/main/resources/db/migration/V88__add_pni_rules.sql

APG-273 Change pni_rule table id to UUID

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt

APG-273 Add logging

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt

APG-273 Fix logging issue

---

build.gradle.kts

fixed conflict in swagger

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/NeedsScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/PniScore.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt

APG-274 Return validation errors as part of PNI response

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/PNIResult.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/PNIController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/main/resources/db/migration/V89__add_pni_results.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt

Save PNI results

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

remove mod security to see if this is causing our prometheus errors

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/Relationships.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/OasysTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysApiIntegrationTest.kt

added missing field

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralStatusHistory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralStatusHistoryService.kt

added reason and category descriptions

---

.circleci/config.yml

fix gradle issue

---

.circleci/config.yml
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Rollback dependency fix

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/PniResultEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/PNIResultEntityRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/simulations/__files/assessments_A1234AA_PACT.json
src/test/resources/simulations/__files/assessments_C6666CC.json
src/test/resources/simulations/__files/assessments_C6666DD.json
src/test/resources/simulations/__files/prison-search-results_A1234AA.json
src/test/resources/simulations/__files/prison-search-results_A9999BB.json
src/test/resources/simulations/__files/prison-search-results_A999BB.json
src/test/resources/simulations/__files/sentence-info_A1234AA_PACT.json
src/test/resources/simulations/mappings/oasys.json
src/test/resources/simulations/mappings/prison-api.json
src/test/resources/simulations/mappings/prison-search-api.json

APG-309 Store PNI when referral is created

---

doc/app-insights/ACP Performance metrics PROD.json
doc/app-insights/ACP-Assess - PROD.json
doc/app-insights/ACP-Dashboard - DEV.json
doc/app-insights/ACP-Find - PROD.json
doc/app-insights/ACP-Refer - PROD.json
doc/app-insights/Refer & Monitor - Accredited Programmes UI (WIP).json

APG-311 backup app insights queries

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

APG-309 Do not throw exception when PNI fails when creating a referral

---

.circleci/config.yml
gradle/wrapper/gradle-wrapper.properties
gradlew.bat

Rollback gradle upgrade

---

.circleci/config.yml
Dockerfile
gradle/wrapper/gradle-wrapper.properties

Update gradle to gradle-8.10

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/StatisticsController.kt

APG-219 Create PNI reporting pathway

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt

APG-366 Fix bug when updating an existing course with an offering

---

src/main/resources/db/migration/V91__fix_hint_text_typo.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

[APG-321] Fix typo in status transition hint text

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/PNIController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/PniScore.kt

Update PNI swagger

---

build.gradle.kts
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/EnabledOrganisationsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/AuditEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseParticipationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/EnabledOrganisationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/OfferingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/OrganisationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PersonEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferralEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/ReferrerUserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/OrganisationControllerTest.kt

APG-322 Remove usage of bluegroundltd:kfactory in tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt

[APG-380] - fix optimistic locking

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/referencedata/ReferralStatusEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralStatusUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt
src/main/resources/db/migration/V92__custom_case_note_message.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PersonEntityFactory.kt

[APG-327] Creating case note on status change

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt

[APG-370] search by name with comma returns expected results

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/DomainEventsListenerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatisticsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatusHistoryIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt
src/test/resources/simulations/__files/prison-register-all-prisons-results.json

Apg 350 prevent duplicates

---

postman/collections/Accredited Programmes API.postman_collection.json

- Added all endpoints from AP API
- Reorganized the structure of the Postman collection to group related items. 
- Added some test data to allow testing against dev
- Updated variable names for HMPPS Auth 

Refactor Postman collection structure and endpoints.

---

.gitignore
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/RiskScores.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/IndividualRiskScores.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/PniIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngineTest.kt

APG-451 Update PNI logic

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt

Minor change in case notes message

---

.circleci/config.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StatisticsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/StatisticsController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/StatisticsIntegrationTest.kt

[APG-432] Return referral count by status

---

postman/collections/Accredited Programmes API.postman_collection.json
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/caseNotesApi/model/CaseNoteRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/OrganisationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt

Minor changes

---

postman/collections/Accredited Programmes API.postman_collection.json
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt

New endpoint to update specific prisoners

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/OfferingRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

[APG-467] Return all courses and offerings

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

APG-467 Address review comments

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/StatisticsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt

Apg 442 referral submit validation from draft

---

.circleci/config.yml

Update playwright image to 1.48.1

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/config/WebClientConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/CourseVariantEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/health/HealthCheck.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/Course.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralIntegrationTest.kt

APG-513 - New endpoint for building choices courses 

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt

[APG-513] Exclude audience when searching building choices for female only orgs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/IndividualNeedsScores.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniNeedsEngine.kt

Revised the scoring methods to return zero instead of null, ensuring consistency in score calculations. Updated the overall needs score computation to sum non-null values directly.

APG-481 - Refactor Overall Needs Score

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/resources/db/migration/V99__update_referral_status_values.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/OfferingControllerTest.kt

Update referral status ref data for confirmation text
- Add SQL script to update `confirmation_text` for various referral statuses. 
- Adjust test methods to validate the new confirmation text.

[APG-450] Update referral status confirmation text

---

src/main/resources/db/migration/V102__update_building_choice_prerequisite_needs_criteria.sql

[APG-574] Update needs criteria content on building choices courses

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/type/SaraRisk.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngineTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/type/SaraRiskTest.kt

- Updated PniRiskEngine to handle Oasys OSP scores of Very High
- Updated corresponding tests
- Additionally updated the SaraRisk handling for Very High scores 

[APG-575] Enhance very high osp risk handling

---

src/main/resources/db/migration/V104__update_organisation_name.sql

[APG-588] Update HOI org name

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/nomisUserRoleManagementApi/model/StaffDetailResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/StaffEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StaffRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/StaffDetail.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/NomisUserRolesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/StaffEntityFactory.kt

[APG-454] Check if staff details exisit in db before fetching

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/StaffEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/StaffEntityFactory.kt

[APG-454] Change account type to string

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt

[APG-598] case notes debug

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngineTest.kt

[APG-599] update PNI high intensity threshold

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt
src/main/resources/db/migration/V107__add_organisations.sql

[APG-598] Additional logging for case notes

---

src/main/resources/db/migration/V107__add_organisations.sql

[APG-598] duplicate id issue when creating orgs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/allocationManagerApi/model/OffenderAllocationResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/nomisUserRoleManagementApi/model/StaffDetailResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/StaffEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/StaffRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/StaffDetail.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/StaffEntityFactory.kt

[APG-455] Fetching POM details as part of referral

---

.circleci/config.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

[APG-577] Update referrals with POMs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/resources/db/migration/V109__update_referral_view.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt

APG-587. Referrals visible in both referer and pom caselists

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/JwtAuthHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt

APG-587 Test for referrals to appear on POM and refers case list view

---

src/main/resources/db/migration/V110__update_org_wakefield.sql

[APG-628] Update org name for WDI as wakefield

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/nomisUserRoleManagementApi/model/StaffDetailResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/StaffEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/StaffDetail.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffService.kt
src/main/resources/db/migration/V111__update_staff.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/StaffEntityFactory.kt

APG-652 Make primaryEmail optional in staff table

---

.circleci/config.yml
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/allocationManagerApi/model/OffenderAllocationResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/listener/DomainEventsListener.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/DomainEventsListenerTest.kt
src/test/resources/simulations/__files/pom_details_487577.json
src/test/resources/simulations/__files/staffDetail_admin_487577.json
src/test/resources/simulations/mappings/allocation-manager-api.json
src/test/resources/simulations/mappings/manage-user-roles-api.json

APG-449 Listen to offender-management.allocation.changed events

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/Course.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/RecordTransformers.kt
src/main/resources/db/migration/V112__update_course_with_intensity.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/DomainEventsListenerTest.kt

APG-629 Preliminary work to map course to intensity

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/Course.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/CourseCreateRequest.kt
src/main/resources/db/migration/V112__update_course_with_intensity.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseEntityFactory.kt

APG-629 Return courses with matching intensity

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngine.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngineTest.kt

• Updated the risk assessment to include both "violence towards others" and "violence towards partner" for determining the highest SARA risk.
• Adjusted tests to reflect the updated logic and ensure alignment with the new evaluation criteria.

[APG-674] Refine SARA risk evaluation logic to consider both risk factors

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngine.kt

[APG-678]  Update risk calculation to include violence towards others for Medium SARA

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/CourseRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt

APG-642 Return audiences specific to course

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/CourseEntityFactory.kt

APG-690 PT journey withdraw referral  - other reason message

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/update/ReferralUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/Referral.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralCreate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralUpdate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/SubjectAccessRequestService.kt
src/main/resources/db/migration/V114__update_referral_add_transferReason_orgReferralId.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/common/config/PersistenceHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

APG-680 add transfer reason and original referralId to referrals

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt

APG-706 New endpoint to fetch duplicate referrals

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

APG-709 Return only building choices courses

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/NeedsScoreFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PniScoreFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/RiskScoreFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/CourseControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/CourseServiceTest.kt

APG-676 Fetch building choices course for a referral

---

build.gradle.kts

APG-696 Potential dependency fix

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/service/ReferralServiceTest.kt

Ensure case notes are published when a referral is transferred to building choices 

APG-682 ensure case notes are published

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/client/oasysApi/model/OasysLearning.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/LearningNeeds.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysServiceTest.kt
src/test/resources/simulations/__files/learning.json

[APG-716] Add problemAreas to oasys learning response

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/ReferralView.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/main/resources/db/migration/V121__update_referral_view.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt

[APG-757] Return hasLdc flag as part of the referral view

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/Course.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/CourseOffering.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt

[APG-776] Return offering along with recommended bc course

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/PNIController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/PrisonNumberRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniRiskEngineTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PniCalculationFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PniResultEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/restapi/controller/ReferralControllerTest.kt

[APG-739] new endpoint to compare pni results

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/listener/DomainEventsListener.kt

[APG-760] ACP listen to probation-case.requirement.created event in dev

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PniService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/PniResponseFactory.kt

[APG-710] Fetch latest ldc score and update referral

---

src/main/resources/db/migration/V124__update_referral_status_for_building_choices.sql

- Added a migration script to update the colour to 'grey' and updated the  closed status to true in `referral_status`

[APG-796] Update referral status for 'MOVED_TO_BUILDING_CHOICES'

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OfferingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/PersonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/unit/domain/entity/factory/OfferingEntityFactory.kt

- Refactored the handling of course assignment in `OfferingEntity` and related factory methods to streamline object construction. 
- Changed the `version` field in `PersonEntity` to be mutable, ensuring consistency with entity updates. 

[APG-756] Refactor course assignment and make version mutable

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt

[APG-777] New endpoint to return other open referrals for a person

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferralTransformers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

- Further increase isolation level
- Revert change to ensure LDC value is persisted on get referral by Id call.

[APG-808] Increase method level Transactional Isolation and revert ldc change

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

- Updated Hibernate and HMPPS starter versions in build configuration
- Removed redundant exception handling and logging in `fetchCompleteReferralDataSetForId` 
- Removed transaction isolation level from `fetchCompleteReferralDataSetForId` method in referral service

[APG-808] Bump up hibernate version

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt

- Refactor CourseEntity to manage prerequisites immutably

[APG-808] Refactor CourseEntity to manage prerequisites immutably

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

APG-811 New admin endpoint to update ldc on existing referrals

---

src/main/resources/db/migration/V127__set_has_ldc_to_null_.sql

[APG-811] Update has_ldc flag to null

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt

- Updated referral submission processing to handle nullable 'additionalInformation' 

[APG-826] Refactor referral submission validation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/LearningNeeds.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/OasysService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/OasysControllerIntegrationTest.kt

- Introduce LDC score retrieval and integration within the LearningNeeds model. 
- Updated the service layer to fetch and include the LDC score, and adjusted the model constructor to handle the new parameter. 
- Updated test cases to reflect this change.

[APG-838] Ensure LDC score is returned with LearningNeeds model 

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/resources/application.yml
src/test/resources/application-test-h2.yml
src/test/resources/application-test.yml

[APG-852] Removing env variable from application.yaml

---

src/main/resources/db/migration/V131__add_sexual_offence_details_table_and_data.sql

- Added check for extant data prior to attempting to insert ref data in table

[APG-886] add check for extant data prior to insert

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/SexualOffenceDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/transformer/ReferenceDataTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferenceDataControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/StaffServiceTest.kt

- **refactor(StaffServiceTest.kt): Don't use inline variable in a test expectation, to make the test more resilient**
- **fix(ReferenceDataController): Remove an errenous 4xx response code**
- **fix(SexualOffenceDetails): Update documentation and types**

Gardening: Improve the SexualOffenceDetails model

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/view/ReferralViewEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/ReferralController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/ReferralControllerIntegrationTest.kt

[APG-900] New endpoint to return HSP referrals

---

src/main/resources/db/migration/V137__delete_hsp_offerings_per_location.sql

- Added a migration script to remove HSP-related offerings for non-UK nationwide organisations.

[APG-923] Delete HSP offerings not tied to NAT organization

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/CourseController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CourseService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/CourseControllerIntegrationTest.kt

Add courseId and offeringId to log message when deleting an offering

---

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/integration/HealthySexProgrammeReferralControllerIntegrationTest.kt

- Fix for flaky test in HSPReferralControllerIntegrationTest

[APG-924] Fix flaky integration test

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

APG-911 Update all prisoners to have updated POM data

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/repository/ReferralRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/ReferralService.kt

[APG-911] Modify updatePoms endpoint to update POM data

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/controller/AdminController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/restapi/model/UpdateAuditCaseNotesRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/AuditService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiService.kt
src/main/resources/db/migration/V139__manual_referral_status_change.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/CaseNotesApiServiceTest.kt

[APG-938] Add audit and case notes message

---

src/main/resources/db/migration/V140__update_healthy_sex_programme_intensity.sql

[APG-961] Update HSP course intensity

---

.circleci/config.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/service/PersonService.kt

[APG-922] debug earliest release date calculation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/CourseEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/OfferingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/domain/entity/create/ReferralEntity.kt

[APG-1110] Add toString to entity class for debugging
